window.RF=window.RF||{};
RF.VERSION='2.0.0';
Object.assign(RF.DATA.items,{
  silver_ore:{name:'Silver Ore',icon:'◻️',type:'material',value:18,desc:'Bright ore prized by smiths and occultists.'},
  wolf_fang:{name:'Wolf Fang',icon:'🦷',type:'material',value:11,desc:'Used by hunters and charm-makers.'},
  venison_stew:{name:'Venison Stew',icon:'🥘',type:'food',value:24,desc:'Restores 42 health.',heal:42},
  blackthorn_blade:{name:'Blackthorn Blade',icon:'🗡️',type:'weapon',value:190,damage:13,slot:'main',desc:'+13 melee damage. A cruel, well-balanced sword.'},
  ranger_cloak:{name:'Ranger Cloak',icon:'🧥',type:'armor',value:145,armor:5,slot:'chest',desc:'+5 armour. Weathered but remarkably light.'},
  strange_key:{name:'Black Iron Key',icon:'🔑',type:'quest',value:0,desc:'Warm to the touch despite the cold metal.'}
});
Object.assign(RF.DATA.locations,{
  mill:{name:'Greenvale Mill',icon:'🌾',region:'Greenvale',desc:'The valley granary, mill and livestock market. Busy by day, eerily still after dusk.',neighbors:{greenvale:9,river:13},actions:['forage','talk'],shop:false},
  watchtower:{name:'Eastwatch Tower',icon:'🗼',region:'Greenvale',desc:'A timber watchtower overlooking the eastern road. Guards track smoke and movement beyond the ridge.',neighbors:{crossroads:18,bandit_camp:24},actions:['talk','explore'],lockedFlag:'eastwatchOpen'},
  deep_mine:{name:'The Deep Galleries',icon:'🕳️',region:'Greenvale',desc:'Old workings beneath Greenvale. Timber groans overhead and cold air rises from shafts no map records.',neighbors:{mine:8},actions:['mine','explore'],lockedFlag:'deepMineFound'}
});
RF.DATA.locations.greenvale.neighbors.mill=9; RF.DATA.locations.river.neighbors.mill=13;
RF.DATA.locations.crossroads.neighbors.watchtower=18;
RF.DATA.locations.mine.neighbors.deep_mine=8;
Object.assign(RF.DATA.enemies,{
  cave_spider:{name:'Cave Spider',icon:'🕷️',hp:65,damage:[5,12],armor:1,xp:78,gold:[0,4],drops:[['herb',.25,1],['silver_ore',.18,1]],level:6},
  blackthorn_scout:{name:'Blackthorn Scout',icon:'🏹',hp:72,damage:[6,13],armor:2,xp:92,gold:[10,24],drops:[['arrow',.8,8],['bandit_token',.7,1],['ranger_cloak',.04,1]],level:7},
  captain_voss:{name:'Captain Voss',icon:'👹',hp:175,damage:[10,20],armor:6,xp:360,gold:[65,110],drops:[['blackthorn_blade',1,1],['strange_key',1,1]],level:12}
});
Object.assign(RF.DATA.recipes,{
  venison_stew:{name:'Cook Venison Stew',skill:'cooking',level:4,time:13,inputs:{raw_meat:2,herb:1},outputs:{venison_stew:1},xp:52}
});
RF.DATA.npcs={
  oren:{name:'Oren Vale',icon:'🧔',job:'Merchant',home:'greenvale',schedule:[['greenvale',6,9],['crossroads',9,16],['greenvale',16,24]],condition:s=>s.flags.savedMerchant&&!s.flags.orenMissing,rumours:['Road trade is recovering, slowly.','Blackthorn men have started asking about a map.']},
  mira:{name:'Mira Fen',icon:'👩‍🌾',job:'Miller',home:'mill',schedule:[['mill',5,18],['greenvale',18,21],['mill',21,24]],rumours:['Flour prices jump whenever the east road closes.','Something keeps worrying the sheep after midnight.']},
  halden:{name:'Sergeant Halden',icon:'🛡️',job:'Watch Sergeant',home:'greenvale',schedule:[['watchtower',6,18],['greenvale',18,24]],condition:s=>s.flags.eastwatchOpen,rumours:['Voss is no common roadside thief.','The watch pays for reliable information, not tavern smoke.']},
  elira:{name:'Elira Moss',icon:'🧙‍♀️',job:'Herbalist',home:'greenvale',schedule:[['forest',7,12],['greenvale',12,19],['greenvale',19,24]],rumours:['Fog changes what grows in Whisperwood.','Never brew silver dust with Greenleaf unless you enjoy seeing tomorrow twice.']},
  brann:{name:'Brann Coalhand',icon:'👨‍🏭',job:'Miner',home:'greenvale',schedule:[['mine',6,17],['greenvale',17,22],['greenvale',22,24]],rumours:['There are fresh scratches below the old third gallery.','The deepest tunnels were sealed before my grandfather was born.']}
};
RF.DATA.factions={greenvale:{name:'Greenvale',icon:'🌿'},watch:{name:'Eastwatch',icon:'🛡️'},blackthorn:{name:'Blackthorn',icon:'🗡️'},merchants:{name:'Vale Traders',icon:'🪙'}};
RF.DATA.v2events=[
 {id:'grain_shortage',title:'The Empty Grain Carts',icon:'🌾',once:true,locations:['greenvale','mill'],weight:5,text:'Mira Fen argues with two farmers beside half-empty grain carts. A bridge on the southern road has washed out, and Greenvale may be short of flour for days.',choices:[
   {text:'Help organise rationing',sub:'Speech 3 helps.',result:s=>{s.world.market.food=(s.world.market.food||1)+.22;s.reputation.greenvale=(s.reputation.greenvale||0)+4;RF.addXp(s,'speech',26);s.flags.grainRationing=true;return 'You spend an hour turning panic into lists and promises. Food prices rise, but Greenvale avoids a stampede at the store.';}},
   {text:'Buy grain before everyone else',condition:s=>s.gold>=20,result:s=>{s.gold-=20;RF.addItem(s,'bread',6);s.world.market.food=(s.world.market.food||1)+.35;s.reputation.greenvale=(s.reputation.greenvale||0)-2;s.flags.hoardedGrain=true;return 'You secure a sack before the shelves empty. People notice.';}},
   {text:'Ignore it',result:s=>{s.world.market.food=(s.world.market.food||1)+.4;return 'By evening, bread has become noticeably more expensive.';}}
 ]},
 {id:'night_howl',title:'Howls Beyond the Mill',icon:'🌕',once:true,locations:['mill','greenvale'],weight:5,condition:s=>RF.hour(s)>=20||RF.hour(s)<5,text:'A shepherd bursts into the road shouting that something has scattered the flock near the mill.',choices:[
   {text:'Go with the shepherd',result:s=>{s.flags.nightHuntStarted=true;RF.UI.modal={type:'chain',title:'Tracks in the Mud',icon:'🐾',text:'Beyond the fence you find wolf tracks, and among them a boot print wrapped in black cloth.',choices:[{text:'Follow the wolf tracks',result:ss=>{RF.addXp(ss,'hunting',35);setTimeout(()=>RF.spawnEnemy('wolf'),50);return 'You follow the tracks into the dark. A grey shape lunges from the hedge.';}},{text:'Follow the boot print',result:ss=>{ss.flags.blackthornMillClue=true;ss.flags.eastwatchOpen=true;RF.addXp(ss,'exploration',30);return 'The trail leads east. Someone from Blackthorn has been deliberately cutting fences.';}}]};return null;}},
   {text:'Stay out of it',result:s=>'You hear distant barking until well after midnight.'}
 ]},
 {id:'tax_collector',title:'The Royal Collector',icon:'📜',once:true,locations:['greenvale'],weight:4,text:'A royal tax collector has arrived with two guards and a ledger thick enough to stop an arrow. Local traders are furious.',choices:[
   {text:'Support the traders',result:s=>{s.reputation.merchants=(s.reputation.merchants||0)+5;s.reputation.watch=(s.reputation.watch||0)-1;s.world.market.general=(s.world.market.general||1)-.06;return 'You lend your voice to the traders. The collector trims several fees rather than risk a market strike.';}},
   {text:'Help the collector audit stalls',result:s=>{s.gold+=28;s.reputation.merchants=(s.reputation.merchants||0)-5;s.reputation.watch=(s.reputation.watch||0)+3;RF.addXp(s,'trading',24);return 'Several merchants receive fines. The crown pays you 28 gold for your useful eyes.';}},
   {text:'Pickpocket the collector',condition:s=>s.skills.thieving.level>=2,result:s=>{if(Math.random()<.65){s.gold+=45;RF.addXp(s,'thieving',40);return 'Forty-five royal coins vanish into your pocket.';}s.reputation.watch=(s.reputation.watch||0)-6;s.flags.wanted=true;return 'A guard catches your wrist. You escape the square, but Eastwatch now has your description.';}}
 ]},
 {id:'deep_knocking',title:'Knocking Below',icon:'⛏️',once:true,locations:['deep_mine'],weight:9,text:'Three slow knocks sound from behind a collapsed gallery wall. Then three more. The miners insist nobody is working beyond it.',choices:[
   {text:'Dig toward the sound',result:s=>{s.flags.deepKnockingOpened=true;RF.addXp(s,'mining',65);RF.addItem(s,'silver_ore',2);return 'You widen a gap just enough to see worked stone beyond the natural rock. Something metallic glints in the dust.';}},
   {text:'Mark the wall and leave',result:s=>{s.flags.deepKnockingMarked=true;RF.addXp(s,'exploration',30);return 'You scratch a warning into the support beam. The knocking stops immediately.';}}
 ]}
];
RF.DATA.events.push(...RF.DATA.v2events);
RF.DATA.quests.blackthorn.next='eastwatch_rising';
RF.DATA.quests.eastwatch_rising={name:'Eastwatch Rising',desc:'Blackthorn is more organised than Greenvale believed. Find who commands them.',objectives:[{type:'flag',target:'eastwatchOpen',text:'Gain access to Eastwatch Tower'},{type:'flag',target:'vossRevealed',text:'Learn the name of the Blackthorn commander'},{type:'kill',target:'captain_voss',value:1,text:'Defeat Captain Voss'}],reward:{gold:320,xp:520,item:'blackthorn_blade'}};

RF.hour=s=>Math.floor(s.minute/60)%24;
RF.migrateV2=function(s){if(!s)return s;s.version='2.0.0';s.reputation=s.reputation||{};['greenvale','watch','blackthorn','merchants'].forEach(k=>s.reputation[k]??=0);s.world=s.world||{};s.world.market=s.world.market||{food:1,metal:1,wood:1,general:1};s.world.alert=s.world.alert||0;s.world.news=s.world.news||[];s.world.lastPulse=s.world.lastPulse??s.minute;s.world.daySeed=s.world.daySeed||Math.random();s.world.npcMoments=s.world.npcMoments||{};s.flags=s.flags||{};s.stats=s.stats||{};s.stats.eventsSeen??=0;s.stats.npcsMet??=0;s.stats.worldDays??=s.day||1;return s};
const _new=RF.newGame;RF.newGame=function(...a){return RF.migrateV2(_new(...a))};
if(RF.state)RF.migrateV2(RF.state);
const _load=RF.load;RF.load=function(){return RF.migrateV2(_load())};
const _import=RF.importSave;RF.importSave=function(x){return RF.migrateV2(_import(x))};
RF.npcsHere=function(s){let h=RF.hour(s);return Object.entries(RF.DATA.npcs).filter(([id,n])=>!n.condition||n.condition(s)).filter(([id,n])=>n.schedule.some(([loc,a,b])=>loc===s.location&&h>=a&&h<b)).map(([id,n])=>({id,...n}))};
RF.priceFactor=function(s,id,buy=true){let it=RF.DATA.items[id],cat=(it.type==='food'||id.includes('meat')||id.includes('fish'))?'food':(id.includes('ore')||id.includes('bar')||it.type==='weapon'||it.type==='armor')?'metal':id==='logs'?'wood':'general';let m=s.world?.market?.[cat]||1,trade=Math.max(.72,1-(s.skills.trading.level-1)*.009),rep=1-Math.max(-20,Math.min(30,s.reputation.greenvale||0))*.003;return buy?m*trade*rep:m*(.50+Math.min(.18,(s.skills.trading.level-1)*.006))};
RF.marketPrice=(s,id,buy=true)=>Math.max(1,Math.round(RF.DATA.items[id].value*RF.priceFactor(s,id,buy)*(buy?1.25:1)));
RF.worldPulse=function(s,minutes){if(!s.world)return; s.world.lastPulse+=minutes; if(s.world.lastPulse<30)return; s.world.lastPulse=0;
  Object.keys(s.world.market).forEach(k=>s.world.market[k]+=(1-s.world.market[k])*.035);
  let h=RF.hour(s),here=RF.npcsHere(s); if(here.length&&Math.random()<.14){let n=here[Math.floor(Math.random()*here.length)];let key=n.id+'_'+s.day+'_'+Math.floor(h/4);if(!s.world.npcMoments[key]){s.world.npcMoments[key]=1;let lines={mira:'Mira loads flour sacks onto a farmer’s cart.',oren:'Oren checks seals on a merchant chest before heading for the road.',halden:'Halden questions a traveller beneath the watch banner.',elira:'Elira sorts herbs into bundles by scent.',brann:'Brann emerges grey with mine dust and heads for the inn.'};RF.log(s,lines[n.id]||`${n.name} goes about the day.`)}}
  if(Math.random()<.055){let news=[['A wolf pack is reported near the river.','food',.04],['A wagon of iron reaches Greenvale.','metal',-.08],['Heavy rain slows timber carts.','wood',.09],['A travelling fair is expected within the week.','general',-.04]];let [txt,cat,d]=news[Math.floor(Math.random()*news.length)];s.world.market[cat]=Math.max(.65,Math.min(1.65,s.world.market[cat]+d));s.world.news.unshift(`D${s.day}: ${txt}`);s.world.news=s.world.news.slice(0,8);RF.log(s,`World: ${txt}`,'important')}
};
const _advance=RF.advanceWorld;RF.advanceWorld=function(minutes){let day=RF.state?.day;_advance(minutes);let s=RF.state;if(!s)return;RF.worldPulse(s,minutes);if(s.day!==day){s.stats.worldDays=s.day;s.world.daySeed=Math.random(); if(s.flags.grainRationing)s.world.market.food=Math.max(.9,s.world.market.food-.08); if(s.flags.hoardedGrain&&s.day>2&&!s.flags.hoardingConsequence){s.flags.hoardingConsequence=true;s.reputation.greenvale-=3;RF.log(s,'Word spreads that you hoarded grain during the shortage.','bad')}}};
const _finish=RF.finishActivity;RF.finishActivity=function(a){_finish(a);let s=RF.state;if(!s)return;if(a.type==='mine'&&s.location==='deep_mine'){if(Math.random()<.28){RF.addItem(s,'silver_ore',1);RF.addXp(s,'mining',18);RF.log(s,'A bright seam yields 1 Silver Ore.','good')}if(Math.random()<.13&&!s.combat)RF.spawnEnemy('cave_spider')}if(a.type==='explore'&&s.location==='bandit_camp'&&s.flags.vossRevealed&&!s.flags.vossDefeated&&!s.combat){RF.log(s,'You find the command tent. Captain Voss steps from behind the canvas.','important');RF.spawnEnemy('captain_voss')}if(a.type==='talk'){}};
const _action=RF.action;RF.action=function(a){if(a!=='talk')return _action(a);let s=RF.state,people=RF.npcsHere(s);if(people.length){let n=people[Math.floor(Math.random()*people.length)],line=n.rumours[Math.floor(Math.random()*n.rumours.length)];s.flags['met_'+n.id]=true;s.stats.npcsMet=Object.keys(s.flags).filter(k=>k.startsWith('met_')&&s.flags[k]).length;RF.log(s,`${n.name}: “${line}”`);RF.addXp(s,'speech',6);RF.UI.render(s)}else _action(a)};
const _try=RF.tryEvent;RF.tryEvent=function(force){let s=RF.state,c=RF.DATA.events.filter(e=>(!e.condition||e.condition(s)));let old=RF.DATA.events;RF.DATA.events=c;let r=_try(force);RF.DATA.events=old;if(r)s.stats.eventsSeen=(s.stats.eventsSeen||0)+1;return r};
RF.resolveEvent=function(i){const s=RF.state,m=RF.UI.modal;if(!m)return;let c=m.type==='event'?m.event.choices[i]:m.type==='chain'?m.choices[i]:null;if(!c||(c.condition&&!c.condition(s)))return;let txt=c.result(s);if(RF.UI.modal===m)RF.UI.modal={type:'message',title:m.type==='event'?m.event.title:m.title,text:txt||'The moment passes.'};RF.questCheck(s);RF.save(s);RF.UI.render(s)};
const _travel=RF.finishTravel;RF.finishTravel=function(a){_travel(a);let s=RF.state;if(!s)return;if(s.location==='watchtower'&&s.flags.wanted&&Math.random()<.7){s.speed=0;RF.UI.modal={type:'event',event:{title:'Stopped by Eastwatch',icon:'🛡️',text:'A guard recognises your description and blocks the stair.',choices:[{text:'Pay the fine (35g)',condition:ss=>ss.gold>=35,result:ss=>{ss.gold-=35;ss.flags.wanted=false;ss.reputation.watch+=1;return 'The guard takes the fine and tears your notice from the board.';}},{text:'Run',result:ss=>{ss.reputation.watch-=2;ss.location='crossroads';return 'You vault the roadside ditch and lose them among the hedges.';}}]}};RF.UI.render(s)}};
const _win=RF.winCombat;RF.winCombat=function(){let id=RF.state.combat?.id;_win();let s=RF.state;if(id==='bandit'||id==='blackthorn_scout'){s.reputation.blackthorn-=1;s.reputation.watch+=1;if((s.kills.bandit||0)+(s.kills.blackthorn_scout||0)>=3)s.flags.eastwatchOpen=true}if(id==='brute'&&!s.flags.vossRevealed){s.flags.vossRevealed=true;RF.log(s,'Among the brute’s things is a letter signed “Voss”.','important')}if(id==='captain_voss'){s.flags.vossDefeated=true;s.reputation.watch+=8;s.reputation.blackthorn-=10;RF.log(s,'With Voss defeated, Blackthorn fractures across the valley.','important')}RF.questCheck(s);RF.save(s)};

// V2 UI extensions
const _world=RF.UI.world.bind(RF.UI);RF.UI.world=function(s){let base=_world(s),people=RF.npcsHere(s);let p=`<section class="card"><h3>People Here <span class="tag">LIVE</span></h3><div class="list">${people.length?people.map(n=>`<div class="row"><div class="icon">${n.icon}</div><div class="meta"><b>${n.name}</b><small>${n.job}</small></div></div>`).join(''):'<div class="sub">Nobody notable is here right now.</div>'}</div></section>`;let news=s.world.news.length?`<section class="card"><h3>Valley News</h3><div class="log">${s.world.news.slice(0,4).map(x=>`<div class="important">${x}</div>`).join('')}</div></section>`:'';return base.replace('<section class="card"><h3>World Feed</h3>',p+news+'<section class="card"><h3>World Feed</h3>')};
RF.UI.shop=function(s){let l=RF.DATA.locations[s.location];if(!l.shop)return `<section class="card"><h2>Shop</h2><div class="notice">There is no permanent shop here. Merchants move around the valley during the day.</div></section>`;let stocks=RF.DATA.shopStock.concat(s.flags.savedMerchant?['iron_ore','coal']:[]);let market=s.world.market;return `<section class="card"><h2>Greenvale Market</h2><div class="marketTicker"><span>🍞 Food ×${market.food.toFixed(2)}</span><span>⚒️ Metal ×${market.metal.toFixed(2)}</span><span>🪵 Wood ×${market.wood.toFixed(2)}</span></div><div class="sub">Prices now respond to supply, events, Trading and your reputation.</div><div class="list" style="margin-top:10px">${stocks.map(id=>{let it=RF.DATA.items[id],price=RF.marketPrice(s,id,true);return `<div class="row"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>${it.desc}</small></div><span class="qty">${price}g</span><button data-buy="${id}" data-price="${price}" ${s.gold>=price?'':'disabled'}>Buy</button></div>`}).join('')}</div></section><section class="card"><h3>Sell</h3><div class="list">${Object.entries(s.inventory).filter(([id])=>RF.DATA.items[id]?.value>0).map(([id,q])=>{let it=RF.DATA.items[id],price=RF.marketPrice(s,id,false);return `<div class="row"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>Owned: ${q}</small></div><span class="qty">${price}g</span><button data-sell="${id}" data-price="${price}">Sell 1</button></div>`}).join('')}</div></section>`};
const _char=RF.UI.character.bind(RF.UI);RF.UI.character=function(s){let reps=Object.entries(RF.DATA.factions).map(([id,f])=>`<div class="statbox"><span>${f.icon} ${f.name}</span><b>${s.reputation[id]||0}</b></div>`).join('');return _char(s).replace('</section><section class="card"><h3>Equipment</h3>',`</section><section class="card"><h3>Reputation</h3><div class="statsGrid">${reps}</div></section><section class="card"><h3>Equipment</h3>`) };
const _modal=RF.UI.modalHtml.bind(RF.UI);RF.UI.modalHtml=function(s){let m=this.modal;if(m?.type==='chain')return `<div class="modalBack"><div class="modal"><div style="font-size:42px">${m.icon||'❗'}</div><h2>${m.title}</h2><div class="sub">${m.text}</div><div class="choices">${m.choices.map((c,i)=>`<button class="choice" data-choice="${i}" ${c.condition&&!c.condition(s)?'disabled':''}><b>${c.text}</b>${c.sub?`<small>${c.sub}</small>`:''}</button>`).join('')}</div></div></div>`;return _modal(s)};
RF.migrateV2(RF.state);if(RF.state){RF.log(RF.state,'Realmforge V2 systems awakened: NPC schedules, factions and dynamic markets are now active.','important');RF.save(RF.state);RF.UI.render(RF.state)};
