window.RF=window.RF||{};
RF.VERSION='9.3.0';
RF.V93={};

RF.migrateV93=function(s){
  if(!s)return s;s.version='9.3.0';s.v93=s.v93||{};
  s.v93.inventoryCategory=s.v93.inventoryCategory||s.v92?.inventoryCategory||'all';
  s.v93.shopCategory=s.v93.shopCategory||s.v92?.shopCategory||'all';
  s.v93.bankCategory=s.v93.bankCategory||'all';s.v93.craftCategory=s.v93.craftCategory||'all';
  s.questOffers=s.questOffers||{};s.questAbandoned=s.questAbandoned||{};
  return s;
};
const v93New=RF.newGame;RF.newGame=function(...a){return RF.migrateV93(v93New(...a))};
const v93Load=RF.load;RF.load=function(){return RF.migrateV93(v93Load())};
const v93Import=RF.importSave;RF.importSave=function(x){return RF.migrateV93(v93Import(x))};
if(RF.state)RF.migrateV93(RF.state);

// ---------- Quest expansion ----------
Object.assign(RF.DATA.quests,{
  greenvale_teeth:{name:'Teeth at the Hedgerows',desc:'Something is worrying livestock around Sunmeadow after dusk. Thin the predators before the farmers start losing animals.',objectives:[{type:'kill',target:'wolf',value:4,text:'Defeat 4 Grey Wolves'},{type:'kill',target:'razorback',value:2,text:'Defeat 2 Razorbacks'}],reward:{gold:95,xp:140,item:'cooked_meat'}},
  river_provisions:{name:'River Provisions',desc:'The Crooked Ladle needs fresh river food before the next caravan arrives.',objectives:[{type:'item',target:'fish',value:5,text:'Carry 5 Riverfish'},{type:'skill',target:'fishing',value:3,text:'Reach Fishing level 3'}],reward:{gold:75,xp:105,item:'bread'}},
  miners_due:{name:"A Miner's Due",desc:'Brann needs replacement iron stock after a support collapse swallowed half the good tools.',objectives:[{type:'item',target:'iron_ore',value:8,text:'Carry 8 Iron Ore'},{type:'skill',target:'mining',value:5,text:'Reach Mining level 5'}],reward:{gold:125,xp:165,item:'iron_bar'}},
  woodland_ledger:{name:'The Woodland Ledger',desc:'Elira wants a proper survey of Whisperwood rather than tavern stories and claw-mark arithmetic.',objectives:[{type:'visit',target:'forest',text:'Visit Whisperwood'},{type:'skill',target:'woodcutting',value:6,text:'Reach Woodcutting level 6'},{type:'kill',target:'rogue_stag',value:1,text:'Defeat a Briar Stag'}],reward:{gold:115,xp:175,item:'herb'}},
  ironridge_contract:{name:'Stone and Scale',desc:'Ironridge smiths are paying for proof that the quarry drakes are nesting closer to the work crews.',objectives:[{type:'visit',target:'quarry',text:'Reach Redstone Quarry'},{type:'kill',target:'quarry_drake',value:2,text:'Defeat 2 Stoneback Drakes'}],reward:{gold:260,xp:340,item:'steel_bar'}},
  marsh_medicine:{name:'Bitter Medicine',desc:'Nessa Vale needs ingredients gathered from the fen before another fever runs through Reedmere.',objectives:[{type:'item',target:'redroot',value:4,text:'Carry 4 Redroot'},{type:'item',target:'mooncap',value:2,text:'Carry 2 Mooncaps'},{type:'skill',target:'herblore',value:5,text:'Reach Herblore level 5'}],reward:{gold:180,xp:260,item:'antivenom'}},
  field_notes:{name:'Field Notes: Dangerous Neighbours',desc:'Maelin Quill is compiling practical observations on creatures that object to being observed.',objectives:[{type:'kill',target:'fen_croc',value:2,text:'Defeat 2 Fen Crocodiles'},{type:'kill',target:'lantern_wisp',value:2,text:'Defeat 2 Lantern Wisps'}],reward:{gold:210,xp:300,item:'marsh_charm'}},
  locksmiths_errand:{name:"The Locksmith's Errand",desc:'Cobb Rill insists a respectable locksmith occasionally needs other people to open things for him.',objectives:[{type:'skill',target:'thieving',value:5,text:'Reach Thieving level 5'},{type:'item',target:'lockpick',value:3,text:'Carry 3 Lockpicks'}],reward:{gold:145,xp:220}}
});
RF.V93.questMeta={
  first_steps:{source:'Story',giver:'Your own curiosity',auto:true,summary:'Learn the rhythm of Greenvale and establish yourself as a capable traveller.'},
  missing_caravan:{source:'Story',giver:'Greenvale road rumours',auto:true,summary:'Investigate the caravan that vanished on the eastern road.'},
  blackthorn:{source:'Story',giver:'Blackthorn evidence',auto:true,summary:'Follow the token back to the gang operating beyond Greenvale.'},
  greenvale_teeth:{source:'Greenvale Noticeboard',location:'greenvale',summary:'Cull predators troubling the farms around Sunmeadow.'},
  river_provisions:{source:'Greenvale Noticeboard',location:'greenvale',summary:'Bring fresh fish and prove you know your way around a river.'},
  miners_due:{source:'Brann / Mine Notice',location:'mine',summary:'Replace valuable ore lost after a mine support failure.'},
  woodland_ledger:{source:'Elira',location:'forest',summary:'Help document Whisperwood and its more territorial inhabitants.'},
  ironridge_contract:{source:'Ironridge Contract Board',location:'ironridge',summary:'Reduce dangerous drakes around Redstone Quarry.'},
  marsh_medicine:{source:'Nessa Vale',location:'reedmere',summary:'Gather fen reagents for Reedmere medicine.'},
  field_notes:{source:'Maelin Quill',location:'mirewatch',summary:'Collect practical combat observations on dangerous Mirefen wildlife.'},
  locksmiths_errand:{source:'Cobb Rill',location:'reedmere',summary:'Demonstrate sufficient finesse for a suspiciously legitimate locksmith.'}
};
RF.v93OfferVisible=function(s,id){let q=RF.DATA.quests[id],m=RF.V93.questMeta[id];if(!q||!m||m.auto||s.quests[id]?.done||s.quests[id]?.active)return false;if(m.location&&s.location!==m.location)return false;
  if(id==='ironridge_contract'&&!s.visited?.ironridge)return false;if(['marsh_medicine','locksmiths_errand'].includes(id)&&!s.visited?.reedmere)return false;if(id==='field_notes'&&!s.visited?.mirewatch)return false;return true};
RF.v93AcceptQuest=function(id){let s=RF.state,q=RF.DATA.quests[id];if(!q||s.quests[id]?.done)return;s.quests[id]={active:true,done:false};delete s.questAbandoned[id];RF.log(s,`Quest accepted: ${q.name}`,'important');RF.save(s);RF.UI.modal={type:'questDetail',id};RF.UI.render(s)};
RF.v93AbandonQuest=function(id){let s=RF.state,qs=s.quests[id];if(!qs?.active)return;delete s.quests[id];s.questAbandoned[id]=true;RF.log(s,`Quest abandoned: ${RF.DATA.quests[id]?.name||id}`);RF.save(s);RF.UI.modal=null;RF.UI.render(s)};
RF.v93RewardText=function(q){let r=q?.reward||{},a=[];if(r.gold)a.push(`${r.gold}g`);if(r.xp)a.push(`${r.xp} character XP`);if(r.item&&RF.DATA.items[r.item])a.push(`${RF.DATA.items[r.item].icon} ${RF.DATA.items[r.item].name}`);return a.join(' • ')||'No listed reward'};

// ---------- Dropdown categories ----------
RF.v93Select=function(kind,active){return `<label class="filterSelect"><span>Category</span><select data-v93-filter="${kind}">${RF.v92Cats.map(([id,n])=>`<option value="${id}" ${active===id?'selected':''}>${n}</option>`).join('')}</select></label>`};
RF.v93Req=function(s,id){let it=RF.DATA.items[id],r=RF.itemRequirement?.(it);if(!r)return'';let have=s.skills?.[r.skill]?.level||1;return `${RF.DATA.skills[r.skill]?.name||r.skill} Lv ${r.level}${have<r.level?` • You ${have}`:''}`};

RF.UI.inventory=function(s){let used=RF.packUsed(s),pct=Math.min(100,used/RF.V82.PACK_CAP*100),cat=s.v93.inventoryCategory||'all';let rows=Object.entries(s.inventory).filter(([,q])=>q>0).filter(([id])=>cat==='all'||RF.v92Category(RF.DATA.items[id])===cat).map(([id,q])=>{let it=RF.DATA.items[id];if(!it)return'';let equipped=RF.isEquipped(s,id),req=RF.v93Req(s,id),can=RF.canEquipItem(s,id),state=equipped?'<span class="equipState equipped">EQUIPPED</span>':it.slot?(can?'<span class="equipState">EQUIP</span>':'<span class="equipState locked">LOCKED</span>'):'';return `<button class="row inventoryRow" data-item-detail="${id}"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name} ${state}</b><small>${it.rarity||it.type||'Item'}${req?` • ${req}`:''}</small></div><span class="qty">×${q}</span><span class="chev">›</span></button>`}).join('');return `<section class="card"><div class="questTitle"><h2>Pack</h2><span class="packCount ${used>=RF.V82.PACK_CAP?'full':''}">${used}/${RF.V82.PACK_CAP} slots</span></div><div class="packBar"><div style="width:${pct}%"></div></div>${RF.v93Select('inventory',cat)}${RF.isBankTown(s)?`<button class="action bankOpen" data-open-bank><b>🏦 Open Bank</b><small>Deposit or withdraw stored items</small></button>`:''}<div class="list inventoryList">${rows||'<div class="sub">Nothing in this category.</div>'}</div></section>`};

RF.UI.shop=function(s){let l=RF.DATA.locations[s.location];if(!l?.shop)return `<section class="card"><h2>Shop</h2><div class="notice">There is no permanent shop here.</div></section>`;let stock=RF.v83ShopStock(s),market=s.world?.market||{food:1,metal:1,wood:1},cat=s.v93.shopCategory||'all';let buyRows=stock.filter(id=>cat==='all'||RF.v92Category(RF.DATA.items[id])===cat).map(id=>{let it=RF.DATA.items[id],price=RF.marketPrice?RF.marketPrice(s,id,true):it.value||1,req=RF.v93Req(s,id);return `<button class="row browseRow" data-shop-detail="${id}" data-shop-mode="buy"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>${req?`Requires ${req} • `:''}${it.desc||''}</small></div><span class="qty">${price}g</span><span class="chev">›</span></button>`}).join('');let sellRows=Object.entries(s.inventory).filter(([id,q])=>q>0&&RF.DATA.items[id]?.value>0&&(cat==='all'||RF.v92Category(RF.DATA.items[id])===cat)).map(([id,q])=>{let it=RF.DATA.items[id],price=RF.marketPrice?RF.marketPrice(s,id,false):Math.max(1,Math.floor(it.value*.55)),req=RF.v93Req(s,id);return `<button class="row browseRow" data-shop-detail="${id}" data-shop-mode="sell"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>Owned ×${q}${req?` • ${req}`:''}</small></div><span class="qty">${price}g</span><span class="chev">›</span></button>`}).join('');return `<section class="card"><h2>${RF.v83ShopName(s)}</h2><div class="marketTicker"><span>🍞 ×${(+market.food||1).toFixed(2)}</span><span>⚒️ ×${(+market.metal||1).toFixed(2)}</span><span>🪵 ×${(+market.wood||1).toFixed(2)}</span></div>${RF.v93Select('shop',cat)}<div class="list" style="margin-top:10px">${buyRows||'<div class="sub">No stock in this category.</div>'}</div></section><section class="card"><h3>Sell</h3><div class="list">${sellRows||'<div class="sub">Nothing saleable in this category.</div>'}</div></section>`};

const v93SkillsBase=RF.UI.skills.bind(RF.UI);RF.UI.skills=function(s){let base=v93SkillsBase(s),marker='<section class="card"><h3>Crafting</h3>',idx=base.indexOf(marker),skillsOnly=idx>=0?base.slice(0,idx):base,cat=s.v93.craftCategory||'all';let rows=Object.entries(RF.DATA.recipes).filter(([id,r])=>{let out=Object.keys(r.outputs||{})[0]||id;return cat==='all'||RF.v92Category(RF.DATA.items[out])===cat}).map(([id,r])=>{let out=Object.keys(r.outputs||{})[0]||id,it=RF.DATA.items[out],req=RF.v93Req(s,out),canLevel=(s.skills[r.skill]?.level||1)>=r.level,canMats=RF.hasItems(s,r.inputs);return `<button class="row browseRow" data-recipe-detail="${id}"><div class="icon">${it?.icon||'🛠️'}</div><div class="meta"><b>${r.name}</b><small>${RF.DATA.skills[r.skill]?.name||r.skill} Lv ${r.level}${req?` • Use: ${req}`:''}</small></div><span class="recipeState ${canLevel&&canMats?'ready':''}">${canLevel&&canMats?'READY':!canLevel?`LV ${r.level}`:'MATS'}</span><span class="chev">›</span></button>`}).join('');return `${skillsOnly}<section class="card"><h3>Crafting</h3>${RF.v93Select('craft',cat)}<div class="sub">Tap a recipe to inspect ingredients, crafting skill and any level required to use the result.</div><div class="list">${rows||'<div class="sub">No recipes in this category.</div>'}</div></section>`};

// ---------- Quest journal ----------
RF.UI.quests=function(s){let active=Object.entries(s.quests||{}).filter(([,qs])=>qs.active&&!qs.done),done=Object.entries(s.quests||{}).filter(([,qs])=>qs.done),offers=Object.keys(RF.DATA.quests).filter(id=>RF.v93OfferVisible(s,id));let row=(id,qs,label)=>{let q=RF.DATA.quests[id],m=RF.V93.questMeta[id]||{};if(!q)return'';return `<button class="row quest browseRow ${qs?.done?'done':''}" data-quest-detail="${id}" data-quest-state="${label}"><div class="meta"><div class="questTitle"><b>${q.name}</b><span class="tag">${label}</span></div><small>${m.summary||q.desc}</small></div><span class="chev">›</span></button>`};return `<section class="card"><h2>📜 Quest Journal</h2><div class="sub">Quests are discovered through story events, people, noticeboards and exploration. Tap any entry for objectives, source, requirements and rewards.</div></section>${offers.length?`<section class="card"><h3>Available Here</h3><div class="list">${offers.map(id=>row(id,null,'AVAILABLE')).join('')}</div></section>`:''}<section class="card"><h3>Active</h3><div class="list">${active.length?active.map(([id,qs])=>row(id,qs,'ACTIVE')).join(''):'<div class="sub">No active quests.</div>'}</div></section><section class="card"><h3>Completed</h3><div class="list">${done.length?done.map(([id,qs])=>row(id,qs,'DONE')).join(''):'<div class="sub">No completed quests yet.</div>'}</div></section>`};

// ---------- Developer tab ----------
RF.UI.dev=function(s){let skills=Object.entries(RF.DATA.skills).map(([id,d])=>`<option value="${id}">${d.name}</option>`).join(''),items=Object.entries(RF.DATA.items).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([id,it])=>`<option value="${id}">${it.icon} ${it.name}</option>`).join(''),locs=Object.entries(RF.DATA.locations).map(([id,l])=>`<option value="${id}" ${id===s.location?'selected':''}>${l.icon} ${l.name}</option>`).join(''),quests=Object.entries(RF.DATA.quests).map(([id,q])=>`<option value="${id}">${q.name}</option>`).join('');return `<section class="card devCard"><h2>🛠️ Developer</h2><div class="notice">Testing controls. These change the live save immediately.</div><h3>Player</h3><div class="devGrid"><button data-dev="gold+">+100 Gold</button><button data-dev="gold-">-100 Gold</button><button data-dev="heal">Full Heal</button><button data-dev="damage">Take 25 HP</button><button data-dev="xp+">+250 Character XP</button><button data-dev="clearcrime">Clear Bounty / Heat</button></div><h3>Skill XP</h3><select data-dev-skill>${skills}</select><div class="devGrid"><button data-dev-skillxp="100">+100 XP</button><button data-dev-skillxp="1000">+1000 XP</button><button data-dev-skillxp="-100">-100 XP</button></div><h3>Give / Remove Item</h3><select data-dev-item>${items}</select><input data-dev-itemqty type="number" inputmode="numeric" value="1" min="1"><div class="devGrid"><button data-dev-itemact="give">Give</button><button data-dev-itemact="remove">Remove</button></div><h3>World</h3><select data-dev-location>${locs}</select><div class="devGrid"><button data-dev="teleport">Teleport</button><button data-dev="hour">+1 Hour</button><button data-dev="day">+1 Day</button><button data-dev="weather">Cycle Weather</button></div><h3>Quest Testing</h3><select data-dev-quest>${quests}</select><div class="devGrid"><button data-dev-questact="start">Start</button><button data-dev-questact="complete">Complete</button><button data-dev-questact="reset">Reset</button></div><h3>Utilities</h3><div class="devGrid"><button data-dev="fillhpstam">Restore HP + Stamina</button><button data-dev="packclear">Clear Unequipped Pack</button><button data-dev="reveal">Reveal Locations</button><button data-dev="logstate">Log State Summary</button></div></section>`};

const v93NavBase=RF.UI.nav.bind(RF.UI);RF.UI.nav=function(){let n=[['world','🌍','WORLD'],['map','🗺️','MAP'],['character','🧍','CHAR'],['skills','📊','SKILLS'],['inventory','🎒','PACK'],['quests','📜','QUESTS'],['shop','🪙','SHOP'],['dev','🛠️','DEV']];return `<nav class="bottomnav"><div class="bottomInner v9nav">${n.map(x=>`<button class="navbtn ${this.tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div></nav>`};
const v93PageBase=RF.UI.page.bind(RF.UI);RF.UI.page=function(s){if(this.tab==='dev')return this.dev(s);return v93PageBase(s)};

// ---------- Modals ----------
const v93ModalBase=RF.UI.modalHtml.bind(RF.UI);RF.UI.modalHtml=function(s){let m=this.modal;
 if(m?.type==='questDetail'){let q=RF.DATA.quests[m.id],qs=s.quests[m.id],meta=RF.V93.questMeta[m.id]||{},isOffer=!qs||(!qs.active&&!qs.done);if(!q)return'';let objs=q.objectives.map(o=>`<div class="objective detailObj">${this.objDone(s,o)?'✅':'⬜'} ${o.text}</div>`).join('');return `<div class="modalBack"><div class="modal questModal"><span class="eyebrow">${qs?.done?'COMPLETED':qs?.active?'ACTIVE QUEST':'QUEST OFFER'}</span><h2>📜 ${q.name}</h2><div class="itemDesc">${q.desc}</div><div class="questInfo"><b>Source</b><span>${meta.source||meta.giver||'World event'}</span></div>${meta.giver?`<div class="questInfo"><b>Giver</b><span>${meta.giver}</span></div>`:''}<h3>Objectives</h3>${objs}<h3>Rewards</h3><div class="notice good">${RF.v93RewardText(q)}</div><div class="choices">${isOffer?`<button class="choice" data-quest-accept="${m.id}"><b>Accept Quest</b></button>`:''}${qs?.active?`<button class="choice dangerChoice" data-quest-abandon="${m.id}"><b>Abandon Quest</b><small>You can reacquire it from its source later.</small></button>`:''}<button class="choice" data-quest-close><b>Close</b></button></div></div></div>`}
 if(m?.type==='bank'){let cat=s.v93.bankCategory||'all',pack=Object.entries(s.inventory).filter(([,q])=>q>0).filter(([id])=>cat==='all'||RF.v92Category(RF.DATA.items[id])===cat).map(([id,q])=>{let it=RF.DATA.items[id],eq=RF.isEquipped(s,id),mov=Math.max(0,q-(eq?1:0)),req=RF.v93Req(s,id);return `<div class="bankRow"><span class="bankIcon">${it.icon}</span><div class="meta"><b>${it.name}</b><small>Pack ×${q}${eq?' • EQUIPPED':''}${req?` • ${req}`:''}</small></div><button data-bank-deposit="${id}" ${mov<1?'disabled':''}>+1</button><button data-bank-deposit-all="${id}" ${mov<1?'disabled':''}>All</button></div>`}).join(''),bank=Object.entries(s.bank||{}).filter(([,q])=>q>0).filter(([id])=>cat==='all'||RF.v92Category(RF.DATA.items[id])===cat).map(([id,q])=>{let it=RF.DATA.items[id],req=RF.v93Req(s,id);return `<div class="bankRow"><span class="bankIcon">${it.icon}</span><div class="meta"><b>${it.name}</b><small>Bank ×${q}${req?` • ${req}`:''}</small></div><button data-bank-withdraw="${id}">-1</button><button data-bank-withdraw-all="${id}">All</button></div>`}).join('');return `<div class="modalBack"><div class="modal bankModal"><h2>🏦 Bank</h2>${RF.v93Select('bank',cat)}<h3>Pack</h3><div class="bankList">${pack||'<div class="sub">Nothing in this category.</div>'}</div><h3>Bank</h3><div class="bankList">${bank||'<div class="sub">Nothing stored in this category.</div>'}</div><button class="quietClose" data-close-bank>Close</button></div></div>`}
 let h=v93ModalBase(s);if(['shopDetail','dialogueTradeDetail','recipeDetail'].includes(m?.type)){let id=m.type==='recipeDetail'?(Object.keys(RF.DATA.recipes[m.id]?.outputs||{})[0]||m.id):m.id,req=RF.v93Req(s,id);if(req)h=h.replace('<div class="choices">',`<div class="requirement met">⚔️ Use requirement: ${req}</div><div class="choices">`)}return h};

RF.v93Dev=function(action){let s=RF.state;if(action==='gold+')s.gold+=100;if(action==='gold-')s.gold=Math.max(0,s.gold-100);if(action==='heal')s.player.hp=s.player.maxHp;if(action==='damage')s.player.hp=Math.max(1,s.player.hp-25);if(action==='xp+')RF.addPlayerXp(s,250);if(action==='clearcrime'){s.bounty=0;s.heat=0;if(s.crime){s.crime.bounty=0;s.crime.heat=0}}if(action==='hour')RF.advanceWorld?.(60);if(action==='day')RF.advanceWorld?.(1440);if(action==='weather'){let w=['Clear','Cloudy','Rain','Storm','Fog'],i=w.indexOf(s.weather);s.weather=w[(i+1)%w.length];s.weatherTimer=180}if(action==='fillhpstam'){s.player.hp=s.player.maxHp;s.player.stamina=s.player.maxStamina}if(action==='packclear'){Object.keys(s.inventory).forEach(id=>{if(!RF.isEquipped(s,id))delete s.inventory[id]})}if(action==='reveal'){Object.keys(RF.DATA.locations).forEach(id=>s.visited[id]=true)}if(action==='logstate')RF.log(s,`DEV: Lv ${s.player.level}, ${s.gold}g, ${s.location}, D${s.day} ${Math.floor(s.minute/60)}:${String(Math.floor(s.minute%60)).padStart(2,'0')}`,'important');RF.save(s);RF.UI.render(s)};

const v93BindBase=RF.UI.bind.bind(RF.UI);RF.UI.bind=function(s){v93BindBase(s);
 document.querySelectorAll('[data-v93-filter]').forEach(el=>el.onchange=()=>{let k=el.dataset.v93Filter+'Category';s.v93[k]=el.value;RF.save(s);RF.UI.render(s)});
 document.querySelectorAll('[data-quest-detail]').forEach(b=>b.onclick=()=>{RF.UI.modal={type:'questDetail',id:b.dataset.questDetail};RF.UI.render(s)});document.querySelectorAll('[data-quest-accept]').forEach(b=>b.onclick=()=>RF.v93AcceptQuest(b.dataset.questAccept));document.querySelectorAll('[data-quest-abandon]').forEach(b=>b.onclick=()=>RF.v93AbandonQuest(b.dataset.questAbandon));document.querySelectorAll('[data-quest-close]').forEach(b=>b.onclick=()=>{RF.UI.modal=null;RF.UI.render(s)});
 document.querySelectorAll('[data-dev]').forEach(b=>b.onclick=()=>{if(b.dataset.dev==='teleport'){let id=document.querySelector('[data-dev-location]')?.value;if(id){s.location=id;s.visited[id]=true;s.activity=null;s.combat=null;RF.log(s,`DEV teleport: ${RF.DATA.locations[id].name}`,'important');RF.save(s);RF.UI.render(s)}}else RF.v93Dev(b.dataset.dev)});
 document.querySelectorAll('[data-dev-skillxp]').forEach(b=>b.onclick=()=>{let id=document.querySelector('[data-dev-skill]')?.value,amt=+b.dataset.devSkillxp,sk=s.skills[id];if(!sk)return;sk.xp=Math.max(RF.xpForLevel(sk.level),sk.xp+amt);sk.level=RF.levelFromXp(sk.xp);RF.save(s);RF.UI.render(s)});
 document.querySelectorAll('[data-dev-itemact]').forEach(b=>b.onclick=()=>{let id=document.querySelector('[data-dev-item]')?.value,q=Math.max(1,+document.querySelector('[data-dev-itemqty]')?.value||1);if(b.dataset.devItemact==='give')RF.addItem(s,id,q);else RF.takeItem(s,id,Math.min(q,s.inventory[id]||0));RF.save(s);RF.UI.render(s)});
 document.querySelectorAll('[data-dev-questact]').forEach(b=>b.onclick=()=>{let id=document.querySelector('[data-dev-quest]')?.value;if(!id)return;if(b.dataset.devQuestact==='start')s.quests[id]={active:true,done:false};if(b.dataset.devQuestact==='complete'){s.quests[id]={active:false,done:true}}if(b.dataset.devQuestact==='reset')delete s.quests[id];RF.save(s);RF.UI.render(s)});
};

if(RF.state){RF.migrateV93(RF.state);if(!RF.state.flags.v93Seen){RF.state.flags.v93Seen=true;RF.log(RF.state,'V9.3: richer quest discovery, detailed quest journal, dropdown categories, visible use requirements and developer tools are active.','important');RF.save(RF.state)}RF.UI.render(RF.state)}
