window.RF=window.RF||{};
RF.V95=RF.V95||{};
RF.V95.SCHEMA='9.5.0';
RF.V95.INDEX_KEY='realmforge_v95_slots';
RF.V95.ACTIVE_KEY='realmforge_v95_active';
RF.V95.slotKey=(id,kind)=>`realmforge_v95_${id}_${kind}`;
RF.V95.hash=function(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')};
RF.V95.readIndex=function(){try{let x=JSON.parse(localStorage.getItem(this.INDEX_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}};
RF.V95.writeIndex=function(arr){localStorage.setItem(this.INDEX_KEY,JSON.stringify(arr))};
RF.V95.id=function(){return 's'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)};
RF.V95.envelope=function(s){let payload=JSON.stringify(s);return JSON.stringify({schema:this.SCHEMA,savedAt:Date.now(),checksum:this.hash(payload),payload})};
RF.V95.decode=function(raw){if(!raw)return null;try{let e=JSON.parse(raw);if(!e||typeof e.payload!=='string'||e.checksum!==this.hash(e.payload))return null;let s=JSON.parse(e.payload);return {state:s,savedAt:e.savedAt||0}}catch{return null}};
RF.V95.touchMeta=function(id,s,name){let list=this.readIndex(),i=list.findIndex(x=>x.id===id),old=i>=0?list[i]:null,meta={id,name:name||old?.name||`${s.player?.name||'Wanderer'} Campaign`,created:old?.created||Date.now(),updated:Date.now(),playerName:s.player?.name||'Wanderer',level:s.player?.level||1,day:s.day||1,location:s.location||'greenvale'};if(i>=0)list[i]=meta;else list.unshift(meta);this.writeIndex(list);return meta};
RF.V95.writeSlot=function(id,s,name,forceRecovery=false){
  if(!id||!s)return false;
  try{
    s.version=this.SCHEMA;s.lastReal=Date.now();
    let primaryKey=this.slotKey(id,'primary'),backupKey=this.slotKey(id,'backup'),recoveryKey=this.slotKey(id,'recovery'),tempKey=this.slotKey(id,'temp');
    let next=this.envelope(s);localStorage.setItem(tempKey,next);
    if(!this.decode(localStorage.getItem(tempKey)))throw new Error('Save verification failed');
    let old=localStorage.getItem(primaryKey),meta=this.readIndex().find(x=>x.id===id),lastRecovery=+(localStorage.getItem(this.slotKey(id,'recovery_at'))||0);
    if(old&&this.decode(old)){
      localStorage.setItem(backupKey,old);
      if(forceRecovery||Date.now()-lastRecovery>180000){localStorage.setItem(recoveryKey,old);localStorage.setItem(this.slotKey(id,'recovery_at'),String(Date.now()))}
    }
    localStorage.setItem(primaryKey,next);
    if(!this.decode(localStorage.getItem(primaryKey)))throw new Error('Primary verification failed');
    localStorage.removeItem(tempKey);this.touchMeta(id,s,name||meta?.name);
    localStorage.setItem(this.ACTIVE_KEY,id);
    // Compatibility mirror: this gives the pre-V9.5 bootstrap a current, readable copy before the slot manager takes over.
    localStorage.setItem('realmforge_save',JSON.stringify(s));
    return true;
  }catch(err){console.error('Realmforge save failed',err);return false}
};
RF.V95.migrate=function(s){if(!s)return s;['migrateV2','migrateV3','migrateV4','migrateV5','migrateV6','migrateV7','migrateV8','migrateV81','migrateV82','migrateV83','migrateV9','migrateV91','migrateV92','migrateV93','migrateV94'].forEach(k=>{try{if(typeof RF[k]==='function')s=RF[k](s)||s}catch(e){console.warn(k,e)}});s.version=this.SCHEMA;return s};
RF.V95.readSlot=function(id){for(let kind of ['primary','backup','recovery']){let d=this.decode(localStorage.getItem(this.slotKey(id,kind)));if(d){d.state=this.migrate(d.state);return {...d,kind}}}return null};
RF.V95.activeId=function(){return localStorage.getItem(this.ACTIVE_KEY)||''};
RF.V95.createSlot=function(s,name){let id=this.id();this.writeSlot(id,s,name,true);return id};
RF.V95.rename=function(id,name){name=(name||'').trim().slice(0,40);if(!name)return false;let list=this.readIndex(),m=list.find(x=>x.id===id);if(!m)return false;m.name=name;this.writeIndex(list);return true};
RF.V95.delete=function(id){let list=this.readIndex().filter(x=>x.id!==id);this.writeIndex(list);['primary','backup','recovery','temp','recovery_at'].forEach(k=>localStorage.removeItem(this.slotKey(id,k)));if(this.activeId()===id)localStorage.removeItem(this.ACTIVE_KEY)};
RF.V95.duplicate=function(id,name){let d=this.readSlot(id);if(!d)return null;let copy=JSON.parse(JSON.stringify(d.state));return this.createSlot(copy,name)};
RF.V95.loadSlot=function(id){let d=this.readSlot(id);if(!d)return false;localStorage.setItem(this.ACTIVE_KEY,id);RF.state=d.state;RF.state.speed=1;RF.state.paused=false;localStorage.setItem('realmforge_save',JSON.stringify(RF.state));RF.UI.modal=null;RF.UI.tab='world';RF.log(RF.state,`Campaign loaded${d.kind!=='primary'?` from ${d.kind} recovery copy`:''}.`,'important');RF.V95.writeSlot(id,RF.state);RF.UI.render(RF.state);return true};
RF.V95.saveNow=function(){let id=this.activeId();if(!id&&RF.state)id=this.createSlot(RF.state,`${RF.state.player.name} • Campaign`);return this.writeSlot(id,RF.state,null,true)};
RF.V95.backupSummary=function(id){return ['primary','backup','recovery'].map(kind=>{let d=this.decode(localStorage.getItem(this.slotKey(id,kind)));return {kind,ok:!!d,savedAt:d?.savedAt||0}})};

// Install slot-aware save immediately. Ordinary autosaves use verified primary + previous primary backup.
RF.save=function(s){if(!s)return false;let id=RF.V95.activeId();if(!id){id=RF.V95.createSlot(s,`${s.player?.name||'Wanderer'} • Campaign`);return true}return RF.V95.writeSlot(id,s)};

// New characters create a separate slot instead of overwriting the prior campaign.
const v95OldStartNew=RF.startNew;
RF.startNew=function(name,bg,avatar){let s=RF.newGame(name,bg,avatar);RF.state=s;let base=(name||'Wanderer').trim()||'Wanderer',existing=RF.V95.readIndex().filter(x=>x.name.startsWith(base)).length;RF.V95.createSlot(s,`${base} • Campaign ${existing+1}`);RF.UI.tab='world';RF.UI.render(s)};

RF.V95.navItems=[['world','🌍','World'],['map','🗺️','World Map'],['database','📚','Database'],['character','🧍','Character'],['skills','📊','Skills & Crafting'],['inventory','🎒','Pack & Bank'],['quests','📜','Quests'],['shop','🪙','Shop'],['dev','🛠️','Developer'],['options','⚙️','Options & Saves']];
RF.UI.nav=function(){let cur=RF.V95.navItems.find(x=>x[0]===this.tab)||RF.V95.navItems[0];return `<nav class="bottomnav compactNav"><div class="navSelectWrap"><span class="navCurrent">${cur[1]}</span><select data-main-nav aria-label="Navigate Realmforge">${RF.V95.navItems.map(x=>`<option value="${x[0]}" ${this.tab===x[0]?'selected':''}>${x[1]} ${x[2]}</option>`).join('')}</select></div></nav>`};

RF.UI.options=function(s){let active=RF.V95.activeId(),slots=RF.V95.readIndex().sort((a,b)=>b.updated-a.updated);let rows=slots.map(m=>{let b=RF.V95.backupSummary(m.id),health=b.filter(x=>x.ok).length,loc=RF.DATA.locations[m.location]?.name||m.location,date=new Date(m.updated).toLocaleString();return `<div class="saveSlot ${m.id===active?'activeSlot':''}"><div class="saveSlotHead"><div><b>${m.id===active?'▶ ':''}${m.name}</b><small>${m.playerName} • Lv ${m.level} • Day ${m.day} • ${loc}</small><small>Saved ${date} • ${health}/3 recovery copies healthy</small></div><span class="saveShield">${health===3?'🛡️':health>=2?'✅':'⚠️'}</span></div><div class="saveActions"><button data-slot-load="${m.id}" ${m.id===active?'disabled':''}>Load</button><button data-slot-save="${m.id}" ${m.id!==active?'disabled':''}>Save Now</button><button data-slot-rename="${m.id}">Rename</button><button data-slot-delete="${m.id}" class="dangerMini">Delete</button></div></div>`}).join('');return `<section class="card optionsCard"><h2>⚙️ Options & Campaigns</h2><div class="notice good">V9.5 uses verified multi-slot saves. Every active campaign keeps a primary save, the previous good save, and an older recovery snapshot.</div><h3>Current Campaign</h3><div class="grid2"><button class="action primary" data-save-now><b>💾 Save Now</b><small>Create and verify a fresh recovery point</small></button><button class="action" data-new-campaign><b>✨ New Campaign</b><small>Keep this campaign and create another</small></button><button class="action" data-export><b>📤 Export Backup</b><small>Portable text backup</small></button><button class="action" data-import><b>📥 Import Backup</b><small>Import as a new campaign slot</small></button><button class="action danger" data-restart-campaign><b>♻️ Restart Campaign</b><small>Archive this campaign first, then restart it</small></button></div><h3>Save Slots</h3><div class="saveSlots">${rows||'<div class="sub">No campaign slots yet.</div>'}</div><div class="sub saveFoot">Tip: keep an occasional exported backup outside the browser too. Slot recovery protects against local corruption; an export protects against clearing browser/app storage.</div></section>`};
const v95PageBase=RF.UI.page.bind(RF.UI);RF.UI.page=function(s){if(this.tab==='options')return this.options(s);return v95PageBase(s)};

const v95ModalBase=RF.UI.modalHtml.bind(RF.UI);RF.UI.modalHtml=function(s){let m=this.modal;if(m?.type==='confirmV95')return `<div class="modalBack"><div class="modal"><h2>${m.title}</h2><div class="sub">${m.text}</div><div class="choices"><button class="choice ${m.danger?'dangerChoice':''}" data-v95-confirm><b>${m.confirm||'Confirm'}</b></button><button class="choice" data-v95-cancel><b>Cancel</b></button></div></div></div>`;if(m?.type==='renameV95')return `<div class="modalBack"><div class="modal"><h2>Rename Campaign</h2><div class="field"><label>Save name</label><input data-v95-rename-input maxlength="40" value="${(m.name||'').replaceAll('&','&amp;').replaceAll('"','&quot;')}"></div><div class="choices"><button class="choice" data-v95-rename-save><b>Save Name</b></button><button class="choice" data-v95-cancel><b>Cancel</b></button></div></div></div>`;return v95ModalBase(s)};

RF.V95.confirm=function(title,text,action,data={},danger=false,confirm='Confirm'){RF.UI.modal={type:'confirmV95',title,text,action,data,danger,confirm};RF.UI.render(RF.state)};
RF.V95.doConfirm=function(m){let id=m.data?.id;if(m.action==='load'){RF.V95.saveNow();RF.V95.loadSlot(id);return}if(m.action==='delete'){let was=RF.V95.activeId()===id;RF.V95.delete(id);if(was){let left=RF.V95.readIndex();if(left.length)RF.V95.loadSlot(left[0].id);else{RF.state=null;RF.UI.modal=null;RF.UI.render(null)}}else{RF.UI.modal=null;RF.UI.render(RF.state)}return}if(m.action==='new'){RF.V95.saveNow();RF.UI.modal=null;RF.state=null;RF.UI.render(null);return}if(m.action==='restart'){let active=RF.V95.activeId(),meta=RF.V95.readIndex().find(x=>x.id===active);if(!active||!RF.state)return;RF.V95.saveNow();RF.V95.duplicate(active,`${meta?.name||RF.state.player.name} • Before Restart`);let old=RF.state,fresh=RF.newGame(old.player.name,old.player.background,old.player.avatar);RF.state=RF.V95.migrate(fresh);RF.V95.writeSlot(active,RF.state,meta?.name,true);RF.UI.modal={type:'message',title:'Campaign Restarted',text:'The current slot has been restarted. A separate “Before Restart” archive was created automatically.'};RF.UI.tab='world';RF.UI.render(RF.state);return}};

// Import is now non-destructive: imported backups become a new slot.
RF.importPrompt=function(){let txt=prompt('Paste your Realmforge save backup:');if(!txt)return;try{RF.V95.saveNow();let s=RF.V95.migrate(RF.importSave(txt));let id=RF.V95.createSlot(s,`${s.player?.name||'Imported'} • Imported`);RF.V95.loadSlot(id);RF.UI.modal={type:'message',title:'Backup Imported',text:'Imported as a separate campaign slot. Your existing campaigns were not overwritten.'};RF.UI.render(RF.state)}catch(e){alert('That save could not be read. No existing campaign was changed.')}};

const v95BindBase=RF.UI.bind.bind(RF.UI);RF.UI.bind=function(s){v95BindBase(s);document.querySelector('[data-main-nav]')?.addEventListener('change',e=>{this.tab=e.target.value;this.modal=null;this.render(s)});document.querySelector('[data-save-now]')?.addEventListener('click',()=>{let ok=RF.V95.saveNow();this.modal={type:'message',title:ok?'Campaign Saved':'Save Failed',text:ok?'Primary, previous-save backup and recovery snapshot have been verified.':'The browser could not verify the save. Your previous good copies were left intact.'};this.render(RF.state)});document.querySelector('[data-new-campaign]')?.addEventListener('click',()=>RF.V95.confirm('Start a New Campaign?','Your current campaign will be saved and kept in its slot. You will return to character creation for a new, separate campaign.','new',{},false,'Start New Campaign'));document.querySelector('[data-restart-campaign]')?.addEventListener('click',()=>RF.V95.confirm('Restart This Campaign?','This resets the current character to the beginning. A “Before Restart” archive will be created automatically so the old campaign can still be recovered.','restart',{},true,'Restart Campaign'));document.querySelectorAll('[data-slot-load]').forEach(b=>b.onclick=()=>{let m=RF.V95.readIndex().find(x=>x.id===b.dataset.slotLoad);RF.V95.confirm('Load Campaign?',`Save the current campaign and switch to “${m?.name||'this campaign'}”?`,'load',{id:b.dataset.slotLoad},false,'Save & Load')});document.querySelectorAll('[data-slot-save]').forEach(b=>b.onclick=()=>{let ok=RF.V95.saveNow();RF.UI.modal={type:'message',title:ok?'Saved':'Save Failed',text:ok?'Campaign safely written and verified.':'The new write failed verification. Previous copies remain available.'};RF.UI.render(RF.state)});document.querySelectorAll('[data-slot-rename]').forEach(b=>b.onclick=()=>{let m=RF.V95.readIndex().find(x=>x.id===b.dataset.slotRename);RF.UI.modal={type:'renameV95',id:b.dataset.slotRename,name:m?.name||''};RF.UI.render(RF.state)});document.querySelectorAll('[data-slot-delete]').forEach(b=>b.onclick=()=>{let m=RF.V95.readIndex().find(x=>x.id===b.dataset.slotDelete);RF.V95.confirm('Delete Save Slot?',`Permanently delete “${m?.name||'this campaign'}” and all three local recovery copies? Export it first if you may want it later.`,'delete',{id:b.dataset.slotDelete},true,'Delete Permanently')});document.querySelector('[data-v95-confirm]')?.addEventListener('click',()=>RF.V95.doConfirm({...RF.UI.modal}));document.querySelector('[data-v95-cancel]')?.addEventListener('click',()=>{RF.UI.modal=null;RF.UI.render(RF.state)});document.querySelector('[data-v95-rename-save]')?.addEventListener('click',()=>{let name=document.querySelector('[data-v95-rename-input]')?.value||'';if(RF.V95.rename(RF.UI.modal.id,name)){RF.UI.modal=null;RF.UI.render(RF.state)}})};

// First V9.5 boot: migrate the existing legacy campaign into a verified slot, or restore the selected slot.
(function(){let slots=RF.V95.readIndex(),active=RF.V95.activeId();if(!slots.length&&RF.state){RF.V95.createSlot(RF.V95.migrate(RF.state),`${RF.state.player?.name||'Wanderer'} • Campaign 1`);active=RF.V95.activeId()}else if(active){let d=RF.V95.readSlot(active);if(d){/* The legacy mirror is loaded by main.js first, so retain its just-applied offline progress when it belongs to this same campaign. */let same=RF.state&&RF.state.created&&d.state.created&&RF.state.created===d.state.created;RF.state=RF.V95.migrate(same?RF.state:d.state)}else if(RF.state){let id=RF.V95.createSlot(RF.V95.migrate(RF.state),`${RF.state.player?.name||'Recovered'} • Recovered`);active=id}}else if(slots.length){RF.V95.loadSlot(slots[0].id);return}if(RF.state){RF.state.version=RF.V95.SCHEMA;if(!RF.state.flags)RF.state.flags={};if(!RF.state.flags.v95Seen){RF.state.flags.v95Seen=true;RF.log(RF.state,'V9.5: multi-slot verified campaign saves and compact navigation are active.','important')}RF.V95.writeSlot(RF.V95.activeId(),RF.state);RF.UI.render(RF.state)}})();
