/* Realmforge V11.28.0 — Canonical Action Cadence.
   Owns the historical V8 real-time action cooldown coordinator. */
(() => {
  'use strict';
  const RF=window.RF;
  const fragmentSources={"v8-runtime-config":"RF.V8 = RF.V8 || {\n  actionCooldowns:{work:520,production:600,huntTrack:700,fire:620,forge:650,lock:560,excavate:650,potion:700,combat:850},\n  boostMs:30000,\n  boostRecoveryMs:20000\n};","v8-action-cadence":"// ---------- Real-time action cooldowns ----------\nRF.actionReady=function(g,key,ms){\n  if(!g)return false;const now=Date.now(),until=g.v8CooldownUntil||0;\n  if(now<until){RF.animateDenied('.tapButton, .action.primary, .abilityBtn');return false;}\n  g.v8CooldownUntil=now+(ms||500);g.v8CooldownMs=ms||500;g.v8CooldownKey=key;RF.state.stats.cooldownActions++;RF.ensureCooldownTicker();return true;\n};\nRF.cooldownRemaining=function(g){return Math.max(0,(g?.v8CooldownUntil||0)-Date.now());};\nRF.ensureCooldownTicker=function(){\n  if(RF.v8ActionTicker)return;\n  const tick=()=>{RF.v8ActionTicker=null;let g=RF.actionGame,c=RF.state?.combat,active=(g&&RF.cooldownRemaining(g)>0)||(c&&Math.max(0,(c.v8CooldownUntil||0)-Date.now())>0);if(active){RF.UI.render(RF.state);RF.v8ActionTicker=setTimeout(tick,80);}};RF.v8ActionTicker=setTimeout(tick,80);\n};\nfunction wrapAction(name,key,ms){const base=RF[name];if(typeof base!=='function')return;RF[name]=function(...args){let g=RF.actionGame;if(g&&!RF.actionReady(g,key,ms))return;return base.apply(RF,args);};}\nwrapAction('workTap','work',RF.V8.actionCooldowns.work);\nwrapAction('productionTap','production',RF.V8.actionCooldowns.production);\nwrapAction('huntTrack','huntTrack',RF.V8.actionCooldowns.huntTrack);\nwrapAction('fireTap','fire',RF.V8.actionCooldowns.fire);\nwrapAction('setTumbler','lock',RF.V8.actionCooldowns.lock);\nwrapAction('stokeForge','forge',RF.V8.actionCooldowns.forge);\nwrapAction('hammerForge','forge',RF.V8.actionCooldowns.forge);\nwrapAction('excavateTile','excavate',RF.V8.actionCooldowns.excavate);\n\n// Combat gets a short real-time cadence on top of turn cooldowns.\nRF.combatReady=function(){let c=RF.state?.combat;if(!c)return false;let now=Date.now();if(now<(c.v8CooldownUntil||0)){RF.animateDenied('.abilityGrid');return false;}c.v8CooldownUntil=now+RF.V8.actionCooldowns.combat;c.v8CooldownMs=RF.V8.actionCooldowns.combat;RF.ensureCooldownTicker();return true;};\nconst v8BattleAbilityBase=RF.battleAbility; RF.battleAbility=function(id){if(!RF.combatReady())return;return v8BattleAbilityBase(id);};\nconst v8BattleItemBase=RF.useBattleItem; RF.useBattleItem=function(id){if(!RF.combatReady())return;return v8BattleItemBase(id);};\nconst v8FleeBase=RF.fleeV4; RF.fleeV4=function(){if(!RF.combatReady())return;return v8FleeBase();};\n\n"};
  const installedFragments=[],seen=new Set();
  function runClassic(source,label){const script=document.createElement('script');script.type='text/javascript';script.setAttribute('data-rf-canonical-cadence-fragment',label);script.textContent=source+'\n//# sourceURL=realmforge-canonical:///systems.cadence/fragment/'+label+'\n';(document.head||document.documentElement).appendChild(script);script.remove();}
  function installHistoricalFragment(name){if(seen.has(name))return false;const source=fragmentSources[name];if(typeof source!=='string')throw new Error('Unknown canonical Cadence fragment: '+name);runClassic(source,name);seen.add(name);installedFragments.push(name);return true;}
  RF.Systems.Cadence=RF.Modules.register('systems.cadence',{installHistoricalFragment,installedFragments,fragmentNames:()=>Object.keys(fragmentSources),ready:(g,key,ms)=>RF.actionReady?.(g,key,ms),remaining:g=>RF.cooldownRemaining?.(g)},{owner:'systems',status:'canonical',historicalFragmentCount:Object.keys(fragmentSources).length,extractedIn:'11.28.0'});
})();
