const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},className:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1,nodeType:1,scrollTop:0};}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};const storage=new Map(),math=Object.create(Math);math.random=()=>0.5;class FixedDate extends Date{static now(){return 1779297600000;}}ctx=vm.createContext({console,Math:math,Date:FixedDate,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/',href:'file:///'},history:{state:{},pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:fn=>1,cancelAnimationFrame(){},queueMicrotask:fn=>fn(),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.__app=app;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};ctx.scrollTo=()=>{};ctx.scrollX=0;ctx.scrollY=0;ctx.pageXOffset=0;ctx.pageYOffset=0;document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_22.js','js/dist/data_core_v11_22.js','js/legacy/base/main.js','js/dist/systems_core_v11_22.js','js/legacy/compat_gameplay_encounter_interface_trimmed_v1153.js','js/dist/canonical_v11_22.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_23.js','js/dist/data_core_v11_23.js','js/legacy/base/main.js','js/dist/systems_core_v11_23.js','js/legacy/compat_gameplay_character_progression_trimmed_v1153.js','js/dist/canonical_v11_23.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF,checks={},same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function state(R){const s=R.newGame('Foundations','traveller','🧭');R.state=s;s.location='greenvale';s.gold=5000;s.speed=1;s.paused=false;s.player.level=12;s.player.xp=12100;s.player.maxEnergy=122;s.player.energy=100;s.perkPoints=4;s.perkPointsSpent=s.perkPointsSpent||0;s.perks=s.perks||{};s.stats=s.stats||{};s.stats.perksBought=s.stats.perksBought||0;s.inventory={bread:5,iron_ore:3,logs:2,lockpick:4};s.bank={bread:2,iron_ore:9};for(const k of Object.keys(s.skills||{})){s.skills[k].level=Math.max(10,s.skills[k].level||1);s.skills[k].xp=R.xpForLevel(s.skills[k].level);}R.UI.modal=null;R.actionGame=null;s.activity=null;R.V101.mainMenu=false;return s;}
const sa=state(A),sb=state(B);
// Canonical ownership and exact extracted ancestry.
checks.characterOwner=B.Modules.info('systems.character')?.meta?.status==='canonical'&&same(B.Systems.Character.installedFragments,['v3-perk-core','v3-perk-modifiers','v3-character-perks-ui','v10-character-creator','v10-progression-queue','v10-progression-render-queue']);
checks.inventoryOwner=B.Systems.Inventory.installedStages.includes('js/v10_10.js')&&['v8_2-pack-foundation','v8_2-pack-migration-intake-items','v8_2-bank-actions','v8_2-pack-bank-ui','v8_2-pack-bank-bind','v10_12-pack-ui','v10_12-bank-ui','v10_12-world-bank-stability'].every(x=>B.Systems.Inventory.installedFragments.includes(x));
checks.equipmentOwner=['v3-bulwark-armor','v3-equipment-ui','v8_2-equipment-foundation','v8_2-equipment-actions'].every(x=>B.Systems.Equipment.installedFragments.includes(x));
checks.gatheringOwner=['v8_2-mastery-work','v8_2-mastery-ui','v10-instant-harvest'].every(x=>B.Systems.Gathering.installedFragments.includes(x));
checks.skillsOwner=['v10-skills-ui','v10_12-skills-crafting-ui'].every(x=>B.Systems.Skills.installedFragments.includes(x));
checks.combatOwner=['v3-combat-techniques','v3-combat-win-perks','v3-combat-ui','v8_2-combat-feedback','v10-battle-summary'].every(x=>B.Systems.Combat.installedFragments.includes(x));
checks.travelOwner=B.Systems.Travel.installedFragments.includes('v3-trailwise-travel');checks.devOwner=B.Views.Developer.installedFragments.includes('v10-dev-energy');
// Character creator and final character presentation remain byte-normalized equivalent.
checks.creatorHtml=norm(A.UI.creator())===norm(B.UI.creator());checks.characterHtml=norm(A.UI.character(sa))===norm(B.UI.character(sb));
// Perk mechanics and perk-derived pricing/armour remain equivalent.
checks.canBuyIronblood=A.canBuyPerk(sa,'ironblood')===B.canBuyPerk(sb,'ironblood')&&B.canBuyPerk(sb,'ironblood')===true;
A.buyPerk('ironblood');B.buyPerk('ironblood');checks.buyPerkState=same({rank:A.perkRank(sa,'ironblood'),points:sa.perkPoints,maxHp:sa.player.maxHp,bought:sa.stats.perksBought},{rank:B.perkRank(sb,'ironblood'),points:sb.perkPoints,maxHp:sb.player.maxHp,bought:sb.stats.perksBought});
sa.perks.silver_tongue=2;sb.perks.silver_tongue=2;checks.priceModifier=A.priceFactor(sa,'bread',true)===B.priceFactor(sb,'bread',true)&&A.priceFactor(sa,'bread',false)===B.priceFactor(sb,'bread',false);
sa.perks.bulwark=2;sb.perks.bulwark=2;checks.bulwarkArmor=A.armor(sa)===B.armor(sb);
// Character level-up perk-point hook and V10 milestone queue remain equivalent.
function prepLevel(R,s){R.V10.queue=[];s.player.level=3;s.player.xp=400;s.perkPoints=0;s.player.maxHp=108;s.player.hp=108;s.player.maxStamina=104;s.player.stamina=104;R.addPlayerXp(s,500);return {level:s.player.level,xp:s.player.xp,points:s.perkPoints,queue:R.V10.queue.map(x=>({type:x.type,kind:x.kind,level:x.level}))};}
checks.levelProgression=same(prepLevel(A,sa),prepLevel(B,sb));
// Skill XP queue parity.
function prepSkill(R,s){R.V10.queue=[];s.skills.attack.level=1;s.skills.attack.xp=0;R.addXp(s,'attack',R.xpForLevel(4));return {level:s.skills.attack.level,xp:s.skills.attack.xp,queue:R.V10.queue.map(x=>({type:x.type,kind:x.kind,skill:x.skill,level:x.level}))};}
checks.skillProgression=same(prepSkill(A,sa),prepSkill(B,sb));
// Pack/Bank ancestry and final bank geography/transfer behavior.
checks.packCapacity=A.packCapacity(sa)===B.packCapacity(sb);checks.packUsed=A.packUsed(sa)===B.packUsed(sb);checks.bankGeography=['greenvale','ironridge','reedmere','forest'].every(loc=>{sa.location=loc;sb.location=loc;return A.isBankTown(sa)===B.isBankTown(sb)});sa.location=sb.location='greenvale';
function bankRoundTrip(R,s){R.state=s;s.inventory.bread=5;s.bank.bread=2;R.bankDeposit('bread',false);const dep={p:s.inventory.bread,b:s.bank.bread};R.bankWithdraw('bread',false);return {dep,end:{p:s.inventory.bread,b:s.bank.bread}};}
checks.bankRoundTrip=same(bankRoundTrip(A,sa),bankRoundTrip(B,sb));
// Final modern UI remains identical even though its old ancestry moved owners.
checks.packHtml=norm(A.UI.inventory(sa))===norm(B.UI.inventory(sb));A.UI.modal={type:'bank'};B.UI.modal={type:'bank'};checks.bankHtml=norm(A.UI.modalHtml(sa))===norm(B.UI.modalHtml(sb));A.UI.modal=null;B.UI.modal=null;
checks.skillsHtml=norm(A.UI.skills(sa))===norm(B.UI.skills(sb));checks.equipmentHtml=norm(A.UI.equipmentPage(sa))===norm(B.UI.equipmentPage(sb));
// Mastery math and stable sorting are exact.
const wood=Object.values(A.DATA.resourceDefs).find(x=>x.skill==='woodcutting');const woodB=Object.values(B.DATA.resourceDefs).find(x=>x.skill==='woodcutting');checks.workRequired=A.workRequired(wood)===B.workRequired(woodB);checks.workPower=A.workPower(sa,wood,A.bestTool(sa,'woodcutting'))===B.workPower(sb,woodB,B.bestTool(sb,'woodcutting'));
const bag={bread:1,iron_ore:1,logs:1};checks.sortedEntries=same(A.V1012.sortedEntries(bag).map(x=>x[0]),B.V1012.sortedEntries(bag).map(x=>x[0]));
checks.compatSize=fs.statSync(path.join(root,'js/legacy/compat_gameplay_character_progression_trimmed_v1153.js')).size===189383;
checks.ownership=B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true;checks.schema=B.V95?.SCHEMA==='11.5.3';checks.warningParity=a.__errs.length===b.__errs.length&&a.__errs.every(x=>String(x).includes('modalHTML'))&&b.__errs.every(x=>String(x).includes('modalHTML'));
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,1),newErrors:b.__errs.slice(0,1),fragments:{character:B.Systems.Character.installedFragments,inventory:B.Systems.Inventory.installedFragments,equipment:B.Systems.Equipment.installedFragments,gathering:B.Systems.Gathering.installedFragments,skills:B.Systems.Skills.installedFragments}},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
