const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},className:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1,nodeType:1,scrollTop:0};}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};const storage=new Map(),math=Object.create(Math);math.random=()=>0.5;class FixedDate extends Date{static now(){return 1779297600000;}}ctx=vm.createContext({console,Math:math,Date:FixedDate,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/',href:'file:///'},history:{state:{},pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:fn=>1,cancelAnimationFrame(){},queueMicrotask:fn=>fn(),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.__app=app;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};ctx.scrollTo=()=>{};ctx.scrollX=0;ctx.scrollY=0;ctx.pageXOffset=0;ctx.pageYOffset=0;document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_25.js','js/dist/data_core_v11_25.js','js/legacy/base/main.js','js/dist/systems_core_v11_25.js','js/legacy/compat_gameplay_dungeon_world_events_trimmed_v1153.js','js/dist/canonical_v11_25.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_26.js','js/dist/data_core_v11_26.js','js/legacy/base/main.js','js/dist/systems_core_v11_26.js','js/legacy/compat_gameplay_combat_collection_trimmed_v1153.js','js/dist/canonical_v11_26.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF,checks={},same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function fresh(R,name='V4Parity'){const s=R.newGame(name,'traveller','🧭');R.state=s;s.location='greenvale';s.gold=900;s.speed=1;s.paused=false;s.player.level=25;s.player.hp=s.player.maxHp;s.player.stamina=s.player.maxStamina;for(const k of Object.keys(s.skills||{})){s.skills[k].level=Math.max(20,s.skills[k].level||1);s.skills[k].xp=R.xpForLevel(s.skills[k].level);}s.collection=s.collection||{enemies:{},items:{},npcs:{},abilities:{}};s.collection.enemies=s.collection.enemies||{};s.collection.items=s.collection.items||{};s.collection.npcs=s.collection.npcs||{};s.collection.abilities=s.collection.abilities||{};s.home={owned:false,level:0,wellRestedBattles:0};s.inventory={bread:2,potion:2,field_tonic:1};s.combat=null;s.activity=null;R.UI.modal=null;R.V101.mainMenu=false;return s;}
const sa=fresh(A,'Same'),sb=fresh(B,'Same');
checks.collectionCanonical=B.Modules.info('systems.collection')?.meta?.status==='canonical';
checks.collectionFragments=same(B.Systems.Collection.installedFragments,['v4-collection-item-tracking','v4-collection-ui']);
checks.combatFragments=['v4-combat-move-pools','v4-tactical-combat-core','v4-tactical-combat-ui'].every(x=>B.Systems.Combat.installedFragments?.includes(x));
checks.characterFragment=B.Systems.Character.installedFragments?.includes('v4-character-shell-ui');
checks.propertyFragment=B.Systems.Property.installedFragments?.includes('v4-buy-home');
checks.movePools=['rat','wolf','bandit','brute','cave_spider','captain_voss','gravewarden','ridge_raider'].every(id=>same(A.DATA.enemies[id]?.moves,B.DATA.enemies[id]?.moves));
checks.statusNames=['bleed','poison','burn','exposed','weakened','stagger','guard','riposte','x'].every(id=>A.statusName(id)===B.statusName(id));
checks.abilities=same(A.unlockedAbilities(sa).map(x=>x.id),B.unlockedAbilities(sb).map(x=>x.id));
checks.collectionHtml=norm(A.UI.collectionPanel(sa))===norm(B.UI.collectionPanel(sb));
checks.characterHtml=norm(A.UI.character(sa))===norm(B.UI.character(sb));
A.addItem(sa,'bread',1);B.addItem(sb,'bread',1);checks.itemTrack=sa.collection.items.bread===true&&sb.collection.items.bread===true&&same(sa.collection.items,sb.collection.items);
// Home purchase action parity.
A.buyHome();B.buyHome();checks.buyHome=sa.home.owned===true&&sb.home.owned===true&&sa.gold===sb.gold&&sa.gold===450;
// Fresh tactical battle shape and original V4 tactical renderer parity.
sa.location='forest';sb.location='forest';A.startBattle('wolf');B.startBattle('wolf');
const battleView=s=>({id:s.combat?.id,hp:s.combat?.hp,maxHp:s.combat?.maxHp,turn:s.combat?.turn,phase:s.combat?.phase,forced:s.combat?.forced,cooldowns:s.combat?.cooldowns,playerStatuses:s.combat?.playerStatuses,enemyStatuses:s.combat?.enemyStatuses,log:s.combat?.log,turnBattles:s.stats?.turnBattles});
checks.startBattle=same(battleView(sa),battleView(sb));
checks.combatHtml=norm(A.UI.combat(sa))===norm(B.UI.combat(sb));
// Status helper and damage function parity under deterministic Math.random.
const ta={statuses:[]},tb={statuses:[]};A.addStatus(ta,'bleed',2,1);B.addStatus(tb,'bleed',2,1);checks.addStatus=same(ta,tb)&&A.hasStatus(ta,'bleed')===B.hasStatus(tb,'bleed');
checks.damage=same(A.playerAttackDamage(sa,{power:1,crit:0},false),B.playerAttackDamage(sb,{power:1,crit:0},false));
checks.combatEntry=A.combatAction('defend')===B.combatAction('defend');
checks.compatSize=fs.statSync(path.join(root,'js/legacy/compat_gameplay_combat_collection_trimmed_v1153.js')).size===114791;
checks.compatReduced=114791<129864;
checks.ownership=B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true;
checks.schema=B.V95?.SCHEMA==='11.5.3';checks.version=B.VERSION==='11.26.0';
checks.warningParity=a.__errs.length===b.__errs.length&&a.__errs.every(x=>String(x).includes('modalHTML'))&&b.__errs.every(x=>String(x).includes('modalHTML'));
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,2),newErrors:b.__errs.slice(0,2),owners:{collection:B.Systems.Collection.installedFragments,combat:B.Systems.Combat.installedFragments,character:B.Systems.Character.installedFragments,property:B.Systems.Property.installedFragments}},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
