const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'tools/content_sources_v12_2.json'),'utf8'));
const packs=fs.readdirSync(path.join(root,manifest.contentPackDirectory)).filter(x=>x.endsWith('.js')).sort().map(x=>`${manifest.contentPackDirectory}/${x}`);
const historicalSource=rel=>rel==='js/data/content/legacy/40_recipes_crafting.js'?'tests/fixtures/40_recipes_crafting_pre_v1260.js':rel;
const join=rels=>rels.map(rel=>fs.readFileSync(path.join(root,historicalSource(rel)),'utf8')).join('\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const checks={};
checks.version=manifest.version==='12.2.0';
checks.packDiscovery=packs.length===1&&packs[0]==='js/data/content/packs/10_forge_and_fletch.js';
checks.baseRepro=join(manifest.baseContentSources)===fs.readFileSync(path.join(root,'js/data/base_content.js'),'utf8');
checks.dataRepro=join([...manifest.dataBundleSources,...packs])===fs.readFileSync(path.join(root,'js/dist/data_core_v12_2.js'),'utf8');
checks.baseShape=manifest.baseContentSources.length===11;
checks.dataShape=manifest.dataBundleSources.filter(x=>x.includes('/content/legacy/')).length===11&&manifest.dataBundleSources.filter(x=>x.includes('/config/')).length===7;
checks.noOldMonoliths=!manifest.dataBundleSources.includes('js/data/content_blocks_v11_9.js')&&!manifest.dataBundleSources.includes('js/data/world_config_v11_10.js');
const pack=fs.readFileSync(path.join(root,packs[0]),'utf8');
checks.declarativePack=pack.includes('A.registerPack(')&&pack.includes("'gathering.content.v12_1_forge_fletch'")&&!pack.includes('RF.DATA.items.')&&!pack.includes('RF.DATA.recipes.');
const data=fs.readFileSync(path.join(root,'js/dist/data_core_v12_2.js'),'utf8');
console.log(JSON.stringify({checks,manifest:{baseSources:manifest.baseContentSources.length,dataSources:manifest.dataBundleSources.length,packs},hashes:{base:sha(fs.readFileSync(path.join(root,'js/data/base_content.js'))),data:sha(data)}},null,2));
if(Object.values(checks).some(v=>!v))process.exit(2);
