const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},className:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1,nodeType:1,scrollTop:0};}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};const storage=new Map(),math=Object.create(Math);math.random=()=>0.5;class FixedDate extends Date{static now(){return 1779297600000;}}ctx=vm.createContext({console,Math:math,Date:FixedDate,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/',href:'file:///'},history:{state:{},pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:fn=>1,cancelAnimationFrame(){},queueMicrotask:fn=>fn(),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.__app=app;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};ctx.scrollTo=()=>{};ctx.scrollX=0;ctx.scrollY=0;ctx.pageXOffset=0;ctx.pageYOffset=0;document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_24.js','js/dist/data_core_v11_24.js','js/legacy/base/main.js','js/dist/systems_core_v11_24.js','js/legacy/compat_gameplay_world_actions_specialist_trimmed_v1153.js','js/dist/canonical_v11_24.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_25.js','js/dist/data_core_v11_25.js','js/legacy/base/main.js','js/dist/systems_core_v11_25.js','js/legacy/compat_gameplay_dungeon_world_events_trimmed_v1153.js','js/dist/canonical_v11_25.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF,checks={},same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function fresh(R,name='DungeonWorld'){const s=R.newGame(name,'traveller','🧭');R.state=s;s.location='crypt';s.gold=5000;s.speed=1;s.paused=false;s.player.level=30;s.player.maxEnergy=150;s.player.energy=120;s.day=12;s.minute=13*60;s.flags=s.flags||{};s.visited=s.visited||{};['greenvale','ironridge','crypt','ember_cave','mine','forest','northroad'].forEach(id=>{if(R.DATA.locations[id])s.visited[id]=true});for(const k of Object.keys(s.skills||{})){s.skills[k].level=Math.max(25,s.skills[k].level||1);s.skills[k].xp=R.xpForLevel(s.skills[k].level);}s.inventory={...(s.inventory||{}),bread:4,potion:4,lockpick:4};s.guild=s.guild||{};s.guild.joined=true;s.guild.contracts=[];s.guild.lastContractDay=0;s.factionWar=s.factionWar||{tension:10,lastShiftDay:1};R.UI.modal=null;s.activity=null;s.combat=null;R.V101.mainMenu=false;return s;}
const sa=fresh(A,'Same'),sb=fresh(B,'Same');
checks.dungeonsCanonical=B.Modules.info('systems.dungeons')?.meta?.status==='canonical';
checks.v114Canonical=B.Systems.Dungeons.installedStages?.includes('js/v11_4.js');
checks.v3DungeonUiCanonical=B.Systems.Dungeons.installedFragments?.includes('v3-delve-action-ui');
checks.worldEventsCanonical=B.Modules.info('systems.worldEvents')?.meta?.status==='canonical';
checks.worldEventsFragments=same(B.Systems.WorldEvents.installedFragments,['v3-world-events','v4-forced-world-events']);
checks.worldEcologyFragment=B.Systems.World.installedFragments?.includes('v4-encounter-ecology-core');
checks.encounterUiFragment=B.Systems.Encounters.installedFragments?.includes('v4-nearby-enemies-ui');
checks.worldActionsFragments=['v3-world-dungeon-crime-ui','v4-modal-composition','v4-world-encounter-social-composition','v4-region-home-composition','v4-bind-composition'].every(x=>B.Views.WorldActions.installedFragments?.includes(x));
checks.dungeonCount=Object.keys(B.V1062?.DUNGEONS||{}).length===8&&Object.keys(A.V1062?.DUNGEONS||{}).length===8;
checks.v114Validate=same(A.V114?.validate?.(),B.V114?.validate?.())&&B.V114?.validate?.().badDungeon?.length===0&&B.V114?.validate?.().badEco?.length===0;
checks.dungeonDefs=same(A.V1062?.DUNGEONS,B.V1062?.DUNGEONS);
checks.ecology=same(A.fieldTables,B.fieldTables);
checks.nearbyHtml=norm(A.UI.nearbyEnemies(sa))===norm(B.UI.nearbyEnemies(sb));
checks.regionMap=norm(A.UI.regionMap(sa))===norm(B.UI.regionMap(sb));
checks.delveButton=norm(A.UI.actionButton('delve',sa))===norm(B.UI.actionButton('delve',sb));
checks.worldHtml=norm(A.UI.world(sa))===norm(B.UI.world(sb));
checks.dungeonDb=same(A.V113?.dungeonEntries?.(sa),B.V113?.dungeonEntries?.(sb));
// Exercise both world-pulse wrapper stacks under deterministic randomness and compare persistent outputs.
A.worldPulse(sa,60);B.worldPulse(sb,60);checks.worldPulseState=same({guild:sa.guild,factionWar:sa.factionWar,news:sa.world?.news,market:sa.world?.market,modal:sa.UI?.modal},{guild:sb.guild,factionWar:sb.factionWar,news:sb.world?.news,market:sb.world?.market,modal:sb.UI?.modal});
checks.compatSize=fs.statSync(path.join(root,'js/legacy/compat_gameplay_dungeon_world_events_trimmed_v1153.js')).size===129864;
checks.compatReduced=129864<148946;
checks.ownership=B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true;
checks.schema=B.V95?.SCHEMA==='11.5.3';checks.version=B.VERSION==='11.25.0';
checks.warningParity=a.__errs.length===b.__errs.length&&a.__errs.every(x=>String(x).includes('modalHTML'))&&b.__errs.every(x=>String(x).includes('modalHTML'));
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,2),newErrors:b.__errs.slice(0,2),owners:{dungeonsStages:B.Systems.Dungeons.installedStages,dungeonFragments:B.Systems.Dungeons.installedFragments,worldEvents:B.Systems.WorldEvents.installedFragments,world:B.Systems.World.installedFragments,encounters:B.Systems.Encounters.installedFragments,worldActions:B.Views.WorldActions.installedFragments}},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
