const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},className:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1,nodeType:1};}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};const storage=new Map(),math=Object.create(Math);math.random=()=>0.5;class FixedDate extends Date{static now(){return 1779297600000;}}ctx=vm.createContext({console,Math:math,Date:FixedDate,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/',href:'file:///'},history:{state:{},pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:fn=>1,cancelAnimationFrame(){},queueMicrotask:fn=>fn(),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.__app=app;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};ctx.scrollTo=()=>{};ctx.scrollX=0;ctx.scrollY=0;ctx.pageXOffset=0;ctx.pageYOffset=0;document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_21.js','js/dist/data_core_v11_21.js','js/legacy/base/main.js','js/dist/systems_core_v11_21.js','js/legacy/compat_gameplay_world_social_trimmed_v1153.js','js/dist/canonical_v11_21.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_22.js','js/dist/data_core_v11_22.js','js/legacy/base/main.js','js/dist/systems_core_v11_22.js','js/legacy/compat_gameplay_encounter_interface_trimmed_v1153.js','js/dist/canonical_v11_22.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF,checks={},same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function state(R){const s=R.newGame('Residual','traveller','🧭');R.state=s;s.day=6;s.minute=14*60;s.location='forest';s.weather='Cloudy';s.speed=1;s.paused=false;s.gold=5000;s.player.level=20;s.player.maxEnergy=140;s.player.energy=100;for(const k of Object.keys(s.skills||{})){s.skills[k].level=Math.max(15,s.skills[k].level||1);s.skills[k].xp=R.xpForLevel(s.skills[k].level);}s.inventory={bread:4,potion:2,lockpick:5,iron_ore:3};s.bank={iron_ore:9};s.v7=s.v7||{};s.v7.research=s.v7.research||{};Object.keys(R.DATA.enemies||{}).slice(0,8).forEach(id=>s.v7.research[id]={level:3,notes:0});R.UI.modal=null;R.actionGame=null;s.activity=null;R.V101.mainMenu=false;return s;}
const sa=state(A),sb=state(B);
checks.ownerEncounter=B.Modules.info('systems.encounters')?.meta?.status==='canonical'&&B.Systems.Encounters.installedFragments.length===2;
checks.ownerItemBrowser=B.Modules.info('ui.itemBrowser')?.meta?.status==='canonical'&&B.Views.ItemBrowser.installedFragments.length===4;
checks.combatFragments=['v8_3-cadence-motion','v9_1-parry-focus','v9_2-defeat-xp'].every(x=>B.Systems.Combat.installedFragments.includes(x));
checks.travelFragment=B.Systems.Travel.installedFragments.includes('v8_3-travel-repair');
checks.crimeFragments=['v9_2-crime-modal-ui','v9_2-crime-bind-ui','v9_2-reedmere-crime-ui'].every(x=>B.Systems.Crime.installedFragments.includes(x));
checks.devFragments=['v9_3-developer-shell','v9_3-developer-actions-bind'].every(x=>B.Views.Developer.installedFragments.includes(x));
checks.nearbyHtml=norm(A.UI.nearbyEnemies(sa))===norm(B.UI.nearbyEnemies(sb));
const aa=A.refreshEncounters(sa),bb=B.refreshEncounters(sb);checks.encounterIds=same(aa.map(x=>x.id),bb.map(x=>x.id));
if(aa[0]&&bb[0]){A.UI.modal={type:'enemyInspect',uid:aa[0].uid,id:aa[0].id};B.UI.modal={type:'enemyInspect',uid:bb[0].uid,id:bb[0].id};checks.inspectModal=norm(A.UI.modalHtml(sa))===norm(B.UI.modalHtml(sb));A.UI.modal=null;B.UI.modal=null;}else checks.inspectModal=true;
checks.categoryBread=A.v92Category(A.DATA.items.bread)===B.v92Category(B.DATA.items.bread);checks.reqParity=A.v93Req(sa,'steel_sword')===B.v93Req(sb,'steel_sword');
// V8.3 travel recovery parity.
sa.v83=sa.v83||{};sb.v83=sb.v83||{};sa.v83.manualPause=false;sb.v83.manualPause=false;sa.activity={type:'travel',duration:20,progress:3,target:'greenvale',from:'forest'};sb.activity=JSON.parse(JSON.stringify(sa.activity));sa.speed=0;sb.speed=0;sa.paused=true;sb.paused=true;checks.travelRepairReturn=A.repairTravelIfStalled()===B.repairTravelIfStalled();checks.travelRepairState=sa.speed===sb.speed&&sa.paused===sb.paused;
// V9.1 training focus parity on a controlled active combat shell.
sa.combat={training:'attack',phase:'player'};sb.combat={training:'attack',phase:'player'};A.v9SetFocus('defence');B.v9SetFocus('defence');checks.focusState=sa.combat.v9Focus===sb.combat.v9Focus&&sb.combat.v9Focus==='defence';
// V9.2 crime modal parity.
const modal={type:'v92PickTargets',targets:[{id:'mira',icon:'🧑',name:'Mira',job:'Trader',passer:false}]};A.UI.modal=JSON.parse(JSON.stringify(modal));B.UI.modal=JSON.parse(JSON.stringify(modal));checks.crimeModal=norm(A.UI.modalHtml(sa))===norm(B.UI.modalHtml(sb));A.UI.modal=null;B.UI.modal=null;
checks.devHtml=norm(A.UI.dev(sa))===norm(B.UI.dev(sb));
checks.compatSize=fs.statSync(path.join(root,'js/legacy/compat_gameplay_encounter_interface_trimmed_v1153.js')).size===235853;
checks.warningParity=a.__errs.length===b.__errs.length&&a.__errs.every(x=>String(x).includes('modalHTML'))&&b.__errs.every(x=>String(x).includes('modalHTML'));
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,1),newErrors:b.__errs.slice(0,1)},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
