const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},className:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1,nodeType:1,scrollTop:0,children:[],matches(){return false}};}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};const storage=new Map(),math=Object.create(Math);math.random=()=>0.5;class FixedDate extends Date{static now(){return 1779297600000;}}ctx=vm.createContext({console,Math:math,Date:FixedDate,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/',href:'file:///'},history:{state:{},pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:fn=>1,cancelAnimationFrame(){},queueMicrotask:fn=>fn(),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.__app=app;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};ctx.scrollTo=()=>{};ctx.scrollX=0;ctx.scrollY=0;ctx.pageXOffset=0;ctx.pageYOffset=0;document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_26.js','js/dist/data_core_v11_26.js','js/legacy/base/main.js','js/dist/systems_core_v11_26.js','js/legacy/compat_gameplay_combat_collection_trimmed_v1153.js','js/dist/canonical_v11_26.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_27.js','js/dist/data_core_v11_27.js','js/legacy/base/main.js','js/dist/systems_core_v11_27.js','js/legacy/compat_gameplay_runtime_residuals_trimmed_v1153.js','js/dist/canonical_v11_27.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF,checks={},same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function fresh(R,name='ResidualParity'){const s=R.newGame(name,'traveller','🧭');R.state=s;s.location='greenvale';s.gold=2000;s.speed=1;s.paused=false;s.player.level=25;s.player.hp=s.player.maxHp;s.player.stamina=s.player.maxStamina;s.player.energy=s.player.maxEnergy||100;for(const k of Object.keys(s.skills||{})){s.skills[k].level=Math.max(20,s.skills[k].level||1);s.skills[k].xp=R.xpForLevel(s.skills[k].level);}s.inventory={...(s.inventory||{}),bread:2,logs:3,lockpick:3,iron_ore:2};s.bank={iron_ore:5,bread:2};s.activity=null;s.combat=null;R.actionGame=null;R.UI.modal=null;R.V101.mainMenu=false;return s;}
const sa=fresh(A,'Same'),sb=fresh(B,'Same');
const fragments={inventory:['v10_9-split-vault'],worldActions:['v10_21-decision-reliability','v3-perk-crime-bind-bridge'],presentation:['v10_11-layout-style','v10_2-skills-crime-style'],appShell:['v10_11-campaign-state-guard'],itemBrowser:['v10_11-category-ordering'],gathering:['v10_1-repaired-gathering'],crime:['v10_1-pickpocket-repair'],overlays:['v10-modal-style','v10-milestone-modal-renderer','v10-modal-bindings'],fieldcraft:['v10_2-campfire-duration'],character:['v10_2-character-skills-grid'],commerce:['v3-ironridge-market-ui'],dungeons:['v3-delve-action-bridge']};
checks.fragmentOwners=fragments.inventory.every(x=>B.Systems.Inventory.installedFragments.includes(x))&&fragments.worldActions.every(x=>B.Views.WorldActions.installedFragments.includes(x))&&fragments.presentation.every(x=>B.Views.Presentation.installedFragments.includes(x))&&fragments.appShell.every(x=>B.Views.AppShell.installedFragments.includes(x))&&fragments.itemBrowser.every(x=>B.Views.ItemBrowser.installedFragments.includes(x))&&fragments.gathering.every(x=>B.Systems.Gathering.installedFragments.includes(x))&&fragments.crime.every(x=>B.Systems.Crime.installedFragments.includes(x))&&fragments.overlays.every(x=>B.Views.Overlays.installedFragments.includes(x))&&fragments.fieldcraft.every(x=>B.Systems.Fieldcraft.installedFragments.includes(x))&&fragments.character.every(x=>B.Systems.Character.installedFragments.includes(x))&&fragments.commerce.every(x=>B.Systems.Commerce.installedFragments.includes(x))&&fragments.dungeons.every(x=>B.Systems.Dungeons.installedFragments.includes(x));
checks.compatSize=fs.statSync(path.join(root,'js/legacy/compat_gameplay_runtime_residuals_trimmed_v1153.js')).size===84320;
checks.compatReduced=84320<114791;
checks.splitVaultObject=!!A.V109&&!!B.V109&&same(A.V109.scroll,B.V109.scroll);
checks.decisionHelpers=A.V1021.safeLevel(sa,'exploration')===B.V1021.safeLevel(sb,'exploration')&&A.V1021.conditionOK({condition:()=>true},sa)===B.V1021.conditionOK({condition:()=>true},sb)&&A.V1021.conditionOK({condition:()=>false},sa)===B.V1021.conditionOK({condition:()=>false},sb);
const stormA=A.DATA.roadEvents?.find(e=>e.id==='sudden_storm'),stormB=B.DATA.roadEvents?.find(e=>e.id==='sudden_storm');checks.stormRepair=!!stormA&&!!stormB&&stormA.choices?.[1]?.sub===stormB.choices?.[1]?.sub;
checks.categorySort=['bread','iron_sword','iron_ore','potion'].filter(id=>A.DATA.items[id]&&B.DATA.items[id]).every(id=>same(A.V1011.itemSortKey(id),B.V1011.itemSortKey(id)))&&A.V1011.compareItemIds('bread','iron_ore')===B.V1011.compareItemIds('bread','iron_ore');
checks.campaignGuard=(()=>{A.V1011.lastState=sa;B.V1011.lastState=sb;A.state=sa;B.state=sb;A.UI.render(null);B.UI.render(null);return A.state===sa&&B.state===sb&&!!A.V1011.lastState&&!!B.V1011.lastState;})();
checks.vigilance=['Guard','Merchant','Farmer','Traveller'].every(job=>A.v9Vigilance({job},false)===B.v9Vigilance({job},false));
const npcId=Object.keys(A.DATA.npcs||{}).find(id=>B.DATA.npcs?.[id]);if(npcId){A.startPickpocket(npcId,false);B.startPickpocket(npcId,false);checks.pickpocketStart=same(A.actionGame,B.actionGame);A.actionGame=null;B.actionGame=null;A.UI.modal=null;B.UI.modal=null;}else checks.pickpocketStart=true;
checks.workTapNoop=(()=>{A.actionGame=null;B.actionGame=null;const ba=JSON.stringify(sa),bb=JSON.stringify(sb);A.workTap();B.workTap();return JSON.stringify(sa)===ba&&JSON.stringify(sb)===bb;})();
A.UI.modal={type:'v10SkillDetail',id:'mining'};B.UI.modal={type:'v10SkillDetail',id:'mining'};checks.skillModal=norm(A.UI.modalHtml(sa))===norm(B.UI.modalHtml(sb));A.UI.modal=null;B.UI.modal=null;
const logId=A.DATA.items?.logs&&B.DATA.items?.logs?'logs':Object.keys(A.DATA.items||{}).find(id=>id.includes('logs')&&B.DATA.items?.[id]);if(logId){sa.inventory[logId]=3;sb.inventory[logId]=3;A.lightFire(logId);B.lightFire(logId);checks.campfire=same(sa.camp,sb.camp)&&sa.inventory[logId]===sb.inventory[logId]&&same(sa.skills.firemaking,sb.skills.firemaking);}else checks.campfire=true;
sa.location='ironridge';sb.location='ironridge';checks.ironridgeShop=norm(A.UI.shop(sa))===norm(B.UI.shop(sb));
sa.location='crypt';sb.location='crypt';sa.activity=null;sb.activity=null;sa.combat=null;sb.combat=null;A.action('delve');B.action('delve');checks.delveAction=same(sa.activity,sb.activity)&&norm(A.UI.actionButton('delve',sa))===norm(B.UI.actionButton('delve',sb));
checks.characterGrid=norm(A.UI.character(sa))===norm(B.UI.character(sb));
checks.ownership=B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true;checks.schema=B.V95?.SCHEMA==='11.5.3';checks.version=B.VERSION==='11.27.0';
checks.warningParity=a.__errs.length===b.__errs.length&&a.__errs.every(x=>String(x).includes('modalHTML'))&&b.__errs.every(x=>String(x).includes('modalHTML'));
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,2),newErrors:b.__errs.slice(0,2),owners:{inventory:B.Systems.Inventory.installedFragments,worldActions:B.Views.WorldActions.installedFragments,presentation:B.Views.Presentation.installedFragments,overlays:B.Views.Overlays.installedFragments}},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
