(() => {
  const RF=window.RF, fail=[];
  const ok=(cond,msg)=>{if(!cond)fail.push(msg)};
  ok(RF.VERSION==='11.16.0','version');
  ok(RF.Core?.contract?.appVersion==='11.16.0','core app version');
  ok(RF.Core?.contract?.saveSchema==='11.5.3','save schema');
  ok(RF.Core?.contract?.architecture==='canonical-systems-v10','core architecture');
  ok(RF.PRODUCTION_FOUNDATION?.architecture==='canonical-systems-v10','architecture');
  ok(RF.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true,'ownership contract');
  ok(RF.Modules?.info?.('systems.exploration')?.meta?.status==='canonical','exploration owner');
  ok(RF.Modules?.info?.('systems.locks')?.meta?.status==='canonical','locks owner');
  ok(RF.Modules?.info?.('systems.crime')?.meta?.status==='canonical','crime owner');
  ok(RF.Modules?.info?.('systems.property')?.meta?.status==='canonical','property owner');
  ok(RF.Systems?.Exploration?.installedStages?.length===3,'exploration stages');
  ok(RF.Systems?.Exploration?.installedFragments?.includes('v7-excavation'),'excavation fragment');
  ok(RF.Systems?.Locks?.installedStages?.length===3,'lock stages');
  ok(RF.Systems?.Crime?.installedStages?.length===6,'crime stages');
  ok(RF.Systems?.Crime?.installedFragments?.length===4,'crime fragments');
  ok(RF.Systems?.Property?.installedStages?.includes('js/v10_24.js'),'property V10.24');
  ok(RF.Systems?.Property?.installedFragments?.length===2,'property fragments');
  ok(RF.Systems?.Fieldcraft?.installedStages?.length===2,'fieldcraft stage ownership reduced');
  ok(typeof RF.V1025?.finishExplore==='function','explore implementation');
  ok(typeof RF.startExcavation==='function'&&typeof RF.excavateTile==='function','excavation implementation');
  ok(typeof RF.V1027?.startLock==='function'&&RF.V1029?.PINS===4&&!!RF.V1032,'lock implementation');
  ok(typeof RF.commitCrime==='function'&&typeof RF.v92BurglaryAttempt==='function'&&typeof RF.V1031?.cooldownRemaining==='function','crime implementation');
  ok(typeof RF.buyHome==='function'&&typeof RF.restAtHome==='function'&&typeof RF.v10RestUntil==='function'&&typeof RF.V1024?.startHomeCook==='function','property implementation');
  ok(RF.Modules?.info?.('systems.cooking')?.meta?.homeKitchenOwner==='systems.property','cooking delegates home kitchen');
  window.RF_TEST_V1116={pass:fail.length===0,fail};
})();
