const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),storage=new Map();let ctx;
function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){}}}
const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};
ctx=vm.createContext({console,Math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:'embedded-runtime.js'})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;
const scripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_9.js','js/dist/data_core_v11_9.js','tests/fixtures/base_main_v1118.js','js/legacy/compat_gameplay_data_trimmed_v1153.js','js/dist/canonical_v11_9.js'];
for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}
const RF=ctx.RF,checks={version:RF.VERSION==='11.9.0',schema:RF.V95?.SCHEMA==='11.5.3',contentOwner:RF.PRODUCTION_FOUNDATION?.contentOwner==='data.catalog',allBlocks:RF.PRODUCTION_FOUNDATION?.contentCore?.allBlocksApplied===true,blockCount:(RF.Content?.appliedLegacyBlocks?.().length||0)===(RF.Content?.expectedLegacyBlocks||-1),items:RF.Catalog?.count('items')===170,enemies:RF.Catalog?.count('enemies')===88,locations:RF.Catalog?.count('locations')===21,equipmentNav:RF.V95?.navItems?.some?.(x=>x[0]==='equipment')===true,toolbeltNav:RF.V95?.navItems?.some?.(x=>x[0]==='toolbelt')===true,noShop:RF.V95?.navItems?.some?.(x=>x[0]==='shop')===false,wayfinder:typeof RF.V1151?.progressHint==='function',catalogValid:(RF.Catalog?.validate?.().length||0)===0};
const known=ctx.__errs.filter(e=>String(e).includes('realmforge-embedded:///v10_9.js:45')),unexpected=ctx.__errs.filter(e=>!String(e).includes('realmforge-embedded:///v10_9.js:45'));
console.log(JSON.stringify({checks,contentCore:RF.PRODUCTION_FOUNDATION?.contentCore,unexpected,known:known.map(x=>String(x).split('\n')[0])},null,2));if(Object.values(checks).some(v=>!v)||unexpected.length)process.exit(2);
