const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
function makeContext(scripts,storage){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){}}}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};ctx=vm.createContext({console,Math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:'embedded-runtime.js'})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const storage=new Map();
const s118=['js/legacy/base/data.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_8.js','js/legacy/base/main.js','js/legacy/compat_gameplay_v1153.js','js/dist/canonical_v11_8.js'];
const s119=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_9.js','js/dist/data_core_v11_9.js','js/legacy/base/main.js','js/legacy/compat_gameplay_data_trimmed_v1153.js','js/dist/canonical_v11_9.js'];
const c118=makeContext(s118,storage),R118=c118.RF;let s=R118.newGame('CluCompat','traveller','🥷');R118.state=s;
s.player.level=29;s.gold=14795;s.location='ironridge';s.equipment={main:'cindermaw_blade',off:'magma_guard',head:'tyrant_crown',chest:'emberplate_cuirass',legs:'tombwarden_greaves',boots:'cinderstep_boots',ring1:'ashglass_ring',ring2:'mireglass_ring'};s.toolBelt={mining:'steel_pickaxe',woodcutting:'steel_axe',fishing:'angler_rod',firemaking:'tinderbox'};s.inventory={...(s.inventory||{}),raw_meat:40,blackroad_feather:6,lockpick:7};s.bank={...(s.bank||{}),iron_ore:55,logs:32};s.flags={...(s.flags||{}),northRoadOpen:true,vossDefeated:true,emberdeepKnown:true};s.v7=s.v7||{};s.v7.research=s.v7.research||{};s.v7.research.blackthorn_scout={level:3,notes:0};s.v1062=s.v1062||{};s.v1062.records=s.v1062.records||{};s.v1062.records.ember_cave={attempts:4,clears:3,bestHp:142};R118.save(s);const id=R118.V95.activeId();R118.V95.saveNow();const before=JSON.parse(JSON.stringify(R118.V95.readSlot(id).state));
const c118reload=makeContext(s118,storage);
const c119=makeContext(s119,storage),R119=c119.RF,after=R119.state;
const checks={slot:R119.V95.activeId()===id,name:after?.player?.name===before.player.name,level:after?.player?.level===29,gold:after?.gold===14795,location:after?.location==='ironridge',equipment:JSON.stringify(after?.equipment)===JSON.stringify(before.equipment),toolBelt:JSON.stringify(after?.toolBelt)===JSON.stringify(before.toolBelt),pack:after?.inventory?.raw_meat===40&&after?.inventory?.blackroad_feather===6,bank:after?.bank?.iron_ore===55,research:after?.v7?.research?.blackthorn_scout?.level===3,flags:after?.flags?.northRoadOpen&&after?.flags?.vossDefeated&&after?.flags?.emberdeepKnown,schema:after?.saveSchema==='11.5.3',content: R119.PRODUCTION_FOUNDATION?.contentCore?.allBlocksApplied===true};
const sig=e=>String(e).split('\n')[0].replace(/^js\/legacy\/base\/main\.js: /,'');const ref=new Set(c118reload.__errs.map(sig));const known=e=>String(e).includes('realmforge-embedded:///v10_9.js:45');const unexpected=c119.__errs.filter(e=>!known(e)&&!ref.has(sig(e)));console.log(JSON.stringify({checks,unexpected,referenceErrors:c118reload.__errs.map(sig),newErrors:c119.__errs.map(sig)},null,2));if(Object.values(checks).some(v=>!v)||unexpected.length)process.exit(2);
