const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts,storage=new Map()){
  let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},onclick:null,offsetWidth:1};}
  const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};
  ctx=vm.createContext({console,Math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});
  ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};
  document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:'embedded-runtime.js'})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;
  for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}
  return ctx;
}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_13.js','js/dist/data_core_v11_13.js','js/legacy/base/main.js','js/dist/systems_core_v11_13.js','js/legacy/compat_gameplay_combat_loadout_trimmed_v1153.js','js/dist/canonical_v11_13.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_14.js','js/dist/data_core_v11_14.js','js/legacy/base/main.js','js/dist/systems_core_v11_14.js','js/legacy/compat_gameplay_research_skills_trimmed_v1153.js','js/dist/canonical_v11_14.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF;const same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function mk(R){let s=R.newGame('MasteryParity','traveller','🧭');R.state=s;s.seed='v1114-parity';s.day=4;s.minute=10*60;s.location='greenvale';s.gold=5000;s.bank=s.bank||{};for(const k of Object.keys(s.skills||{})){s.skills[k].level=20;s.skills[k].xp=R.xpForLevel?R.xpForLevel(20):s.skills[k].xp;}s.inventory={...(s.inventory||{}),copper_ore:20,tin_ore:20,iron_ore:20,coal:20,logs:20,herb:20,raw_meat:20,wild_berries:20};s.v7=s.v7||{};s.v7.research=s.v7.research||{};s.encounters={};s.v1153=s.v1153||{encounterStamps:{}};s.v1153.encounterStamps={};R.UI.modal=null;return s;}
const sa=mk(A),sb=mk(B);
// Research parity: final hourly encounter generation, fieldcraft curve/progress and secrecy UI.
sa.location=sb.location='forest';const ea=A.refreshEncounters(sa,'forest',true),eb=B.refreshEncounters(sb,'forest',true);const encounterSame=same(ea,eb);
const profileSame=same(A.V1152.profile(sa),B.V1152.profile(sb));const progressSame=same(A.V1152.progress({level:1,notes:2},2),B.V1152.progress({level:1,notes:2},2));
const rid=(ea[0]||{}).id;if(rid){sa.v7.research[rid]={level:1,notes:1};sb.v7.research[rid]={level:1,notes:1};}
const researchHtmlSame=norm(A.V1048.fieldResearchHtml(sa))===norm(B.V1048.fieldResearchHtml(sb));const nearbyHtmlSame=norm(A.UI.nearbyEnemies(sa))===norm(B.UI.nearbyEnemies(sb));
// Skills parity: stale level/XP normalization + mastery grid.
sa.location=sb.location='greenvale';sa.skills.smithing.level=1;sb.skills.smithing.level=1;sa.skills.smithing.xp=A.xpForLevel(16);sb.skills.smithing.xp=B.xpForLevel(16);
const effectiveSame=A.effectiveSkillLevel(sa,'smithing')===B.effectiveSkillLevel(sb,'smithing')&&B.effectiveSkillLevel(sb,'smithing')===16;
A.normalizeSkillRequirements(sa);B.normalizeSkillRequirements(sb);const normalizedSame=same(sa.skills.smithing,sb.skills.smithing);const requirementSame=same(A.V112.requirementText(sa,'smithing',16),B.V112.requirementText(sb,'smithing',16));
const skillsHtmlSame=norm(A.UI.skills(sa))===norm(B.UI.skills(sb));
// Crafting parity: workshop recipe analysis/render and batch-start state.
const recipeId=Object.keys(A.DATA.recipes).find(id=>A.DATA.recipes[id]?.skill!=='cooking'&&B.DATA.recipes[id]);const ra=A.DATA.recipes[recipeId],rb=B.DATA.recipes[recipeId];
for(const [id,q] of Object.entries(ra.inputs||{})){sa.inventory[id]=Math.max(sa.inventory[id]||0,q*5);sb.inventory[id]=Math.max(sb.inventory[id]||0,q*5);}sa.skills[ra.skill].level=sb.skills[rb.skill].level=Math.max(25,ra.level,rb.level);sa.skills[ra.skill].xp=A.xpForLevel(sa.skills[ra.skill].level);sb.skills[rb.skill].xp=B.xpForLevel(sb.skills[rb.skill].level);
const analysisSame=same(A.V1028.craftAnalysis(sa,recipeId),B.V1028.craftAnalysis(sb,recipeId));const workshopSame=norm(A.V1028.workshopSection(sa))===norm(B.V1028.workshopSection(sb));
A.v9StartCraftQty(recipeId,2);B.v9StartCraftQty(recipeId,2);const batchSame=!!A.actionGame&&!!B.actionGame&&A.actionGame.type===B.actionGame.type&&A.actionGame.recipe===B.actionGame.recipe&&A.actionGame.v9Qty===B.actionGame.v9Qty&&A.actionGame.v9Target===B.actionGame.v9Target;
const checks={version:B.VERSION==='11.14.0',schema:B.V95?.SCHEMA==='11.5.3',encounterSame,profileSame,progressSame,researchHtmlSame,nearbyHtmlSame,effectiveSame,normalizedSame,requirementSame,skillsHtmlSame,analysisSame,workshopSame,batchSame,
 researchCanonical:B.Modules?.info?.('systems.research')?.meta?.status==='canonical'&&B.Systems.Research.installedStages.length===4,
 craftingCanonical:B.Modules?.info?.('systems.crafting')?.meta?.status==='canonical'&&B.Systems.Crafting.installedStages.length===4,
 skillsCanonical:B.Modules?.info?.('systems.skills')?.meta?.status==='canonical'&&B.Systems.Skills.installedStages.length===2,
 ownership:B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true};
console.log(JSON.stringify({checks,recipeId,researchId:rid,oldErrors:a.__errs.slice(0,8),newErrors:b.__errs.slice(0,8),sizes:{research:B.Systems.Research.installedStages.length,crafting:B.Systems.Crafting.installedStages.length,skills:B.Systems.Skills.installedStages.length}},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
