const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts,storage=new Map()){
  let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},onclick:null,offsetWidth:1};}
  const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};
  const math=Object.create(Math);math.random=()=>0.5;
  ctx=vm.createContext({console,Math:math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});
  ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};
  document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;
  for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}
  return ctx;
}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_15.js','js/dist/data_core_v11_15.js','js/legacy/base/main.js','js/dist/systems_core_v11_15.js','js/legacy/compat_gameplay_fieldcraft_trimmed_v1153.js','js/dist/canonical_v11_15.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_16.js','js/dist/data_core_v11_16.js','js/legacy/base/main.js','js/dist/systems_core_v11_16.js','js/legacy/compat_gameplay_exploration_crime_property_trimmed_v1153.js','js/dist/canonical_v11_16.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF;const same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function fresh(R,name='Parity'){
  const s=R.newGame(name,'traveller','🧭');R.state=s;s.day=5;s.minute=10*60;s.gold=5000;s.location='greenvale';s.player.energy=s.player.maxEnergy||100;
  for(const k of Object.keys(s.skills||{})){s.skills[k].level=20;s.skills[k].xp=R.xpForLevel?R.xpForLevel(20):s.skills[k].xp;}
  s.inventory={...(s.inventory||{}),lockpick:8,fine_lockpick:3,herb:8,wild_berries:8,raw_meat:8,bread:4};s.bank={...(s.bank||{}),raw_meat:8,herb:8};s.home=s.home||{};s.home.owned=true;s.stats=s.stats||{};R.UI.modal=null;R.actionGame=null;s.activity=null;return s;
}
// Static exploration/lock/crime contracts.
let sa=fresh(A,'OldStatic'),sb=fresh(B,'NewStatic');
const chestsSame=same(A.V1025.CHESTS,B.V1025.CHESTS);
const exploreCostSame=A.V1026.exploreEnergyCost(sa)===B.V1026.exploreEnergyCost(sb);
const legacyLocksSame=same(A.V1034?.LEGACY_LOCKS,B.V1034?.LEGACY_LOCKS);
const burglarySitesSame=same(A.v92BurglarySites,B.v92BurglarySites)&&same(A.V1031.SITE_BALANCE,B.V1031.SITE_BALANCE);
const profilesSame=same(['low','medium','rare'].map(x=>A.V1027.chestProfile(sa,x)),['low','medium','rare'].map(x=>B.V1027.chestProfile(sb,x)))&&same(A.V1027.siteProfile(sa,8),B.V1027.siteProfile(sb,8))&&same(A.V1027.burglaryProfile(sa,A.v92BurglarySites.greenvale[0]),B.V1027.burglaryProfile(sb,B.v92BurglarySites.greenvale[0]));
// Explore action parity.
sa=fresh(A,'OldExplore');sb=fresh(B,'NewExplore');sa.location=sb.location='ruins';A.action('explore');B.action('explore');
const exploreStartSame=same({activity:sa.activity&&{type:sa.activity.type,label:sa.activity.label,duration:sa.activity.duration,progress:sa.activity.progress},energy:sa.player.energy},{activity:sb.activity&&{type:sb.activity.type,label:sb.activity.label,duration:sb.activity.duration,progress:sb.activity.progress},energy:sb.player.energy});
// Excavation parity, deterministic secret=4 with Math.random=0.5.
sa=fresh(A,'OldDig');sb=fresh(B,'NewDig');sa.location=sb.location='ruins';A.startExcavation('ruins');B.startExcavation('ruins');const digStartSame=same({type:A.actionGame?.type,secret:A.actionGame?.secret,digs:A.actionGame?.digs},{type:B.actionGame?.type,secret:B.actionGame?.secret,digs:B.actionGame?.digs});A.excavateTile(4);B.excavateTile(4);const digFinishSame=same({inv:sa.inventory,xp:sa.skills.exploration.xp,stats:sa.stats.excavations,exc:sa.v7.excavated.ruins,day:sa.day,minute:sa.minute},{inv:sb.inventory,xp:sb.skills.exploration.xp,stats:sb.stats.excavations,exc:sb.v7.excavated.ruins,day:sb.day,minute:sb.minute});
// Shared four-pin lock initialisation parity.
sa=fresh(A,'OldLock');sb=fresh(B,'NewLock');const pa=A.V1027.chestProfile(sa,'medium'),pb=B.V1027.chestProfile(sb,'medium');A.V1027.startLock({context:'chest',title:'Parity Chest',icon:'🧰',tier:'medium',location:'greenvale',profile:pa});B.V1027.startLock({context:'chest',title:'Parity Chest',icon:'🧰',tier:'medium',location:'greenvale',profile:pb});
const lockStartSame=same({type:A.actionGame?.type,pinStage:A.actionGame?.pinStage,pinRequired:A.actionGame?.pinRequired,tolerance:A.actionGame?.tolerance,difficulty:A.actionGame?.difficulty,arcStroke:A.actionGame?.arcStroke,revSeconds:A.actionGame?.revSeconds},{type:B.actionGame?.type,pinStage:B.actionGame?.pinStage,pinRequired:B.actionGame?.pinRequired,tolerance:B.actionGame?.tolerance,difficulty:B.actionGame?.difficulty,arcStroke:B.actionGame?.arcStroke,revSeconds:B.actionGame?.revSeconds});
// Crime bounty primitives and pickpocket initialisation parity.
sa=fresh(A,'OldCrime');sb=fresh(B,'NewCrime');A.addBounty(sa,42,'parity');B.addBounty(sb,42,'parity');const bountySame=same({b:sa.crime.bounty,h:sa.crime.heat,w:sa.flags.wanted,c:sa.stats.crimes},{b:sb.crime.bounty,h:sb.crime.heat,w:sb.flags.wanted,c:sb.stats.crimes});A.startPickpocket('mira',false);B.startPickpocket('mira',false);const pickStartSame=same({type:A.actionGame?.type,id:A.actionGame?.id,target:A.actionGame?.target,width:A.actionGame?.width,attention:A.actionGame?.attention,vigilance:A.actionGame?.vigilance},{type:B.actionGame?.type,id:B.actionGame?.id,target:B.actionGame?.target,width:B.actionGame?.width,attention:B.actionGame?.attention,vigilance:B.actionGame?.vigilance});
// Burglary site modal/cooldown parity.
sa=fresh(A,'OldBurg');sb=fresh(B,'NewBurg');sa.location=sb.location='greenvale';const siteA=A.v92BurglarySites.greenvale[0],siteB=B.v92BurglarySites.greenvale[0];A.v92ChooseBurglary(siteA.id);B.v92ChooseBurglary(siteB.id);const burgModalSame=same({type:A.UI.modal?.type,id:A.UI.modal?.site?.id},{type:B.UI.modal?.type,id:B.UI.modal?.site?.id});A.V1031.setCooldown(sa,siteA,true);B.V1031.setCooldown(sb,siteB,true);const cooldownSame=A.V1031.cooldownRemaining(sa,siteA)===B.V1031.cooldownRemaining(sb,siteB)&&A.V1031.cooldownRemaining(sa,siteA)===1440;
// Property resting and home-kitchen parity.
sa=fresh(A,'OldHome');sb=fresh(B,'NewHome');for(const s of [sa,sb]){s.location='greenvale';s.player.hp=12;s.player.stamina=13;s.player.energy=14;s.home.owned=true;s.home.wellRestedBattles=0;}A.restAtHome();B.restAtHome();const homeRestSame=same({hp:sa.player.hp,st:sa.player.stamina,en:sa.player.energy,wr:sa.home.wellRestedBattles,day:sa.day,minute:sa.minute},{hp:sb.player.hp,st:sb.player.stamina,en:sb.player.energy,wr:sb.home.wellRestedBattles,day:sb.day,minute:sb.minute});
sa=fresh(A,'OldInn');sb=fresh(B,'NewInn');sa.location=sb.location='greenvale';sa.player.hp=sb.player.hp=5;sa.player.stamina=sb.player.stamina=6;sa.player.energy=sb.player.energy=7;A.v10RestUntil(7);B.v10RestUntil(7);const innRestSame=same({hp:sa.player.hp,st:sa.player.stamina,en:sa.player.energy,day:sa.day,minute:sa.minute,r:sa.stats.innRests},{hp:sb.player.hp,st:sb.player.stamina,en:sb.player.energy,day:sb.day,minute:sb.minute,r:sb.stats.innRests});
sa=fresh(A,'OldKitchen');sb=fresh(B,'NewKitchen');sa.location=sb.location='greenvale';const homePanelSame=norm(A.V1024.homePanel(sa))===norm(B.V1024.homePanel(sb));const needsSame=same(A.V1024.recipeNeeds(A.DATA.campRecipes.venison_stew),B.V1024.recipeNeeds(B.DATA.campRecipes.venison_stew));
const checks={version:B.VERSION==='11.16.0',schema:B.V95?.SCHEMA==='11.5.3',chestsSame,exploreCostSame,legacyLocksSame,burglarySitesSame,profilesSame,exploreStartSame,digStartSame,digFinishSame,lockStartSame,bountySame,pickStartSame,burgModalSame,cooldownSame,homeRestSame,innRestSame,homePanelSame,needsSame,
 explorationCanonical:B.Modules?.info?.('systems.exploration')?.meta?.status==='canonical'&&B.Systems.Exploration.installedStages.length===3&&B.Systems.Exploration.installedFragments.length===1,
 locksCanonical:B.Modules?.info?.('systems.locks')?.meta?.status==='canonical'&&B.Systems.Locks.installedStages.length===3,
 crimeCanonical:B.Modules?.info?.('systems.crime')?.meta?.status==='canonical'&&B.Systems.Crime.installedStages.length===6&&B.Systems.Crime.installedFragments.length===4,
 propertyCanonical:B.Modules?.info?.('systems.property')?.meta?.status==='canonical'&&B.Systems.Property.installedStages.length===1&&B.Systems.Property.installedFragments.length===2,
 fieldcraftReduced:B.Systems.Fieldcraft.installedStages.length===2&&B.Systems.Fieldcraft.installedFragments.length===3,
 cookingDelegates:B.Modules?.info?.('systems.cooking')?.meta?.homeKitchenOwner==='systems.property',ownership:B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true};
console.log(JSON.stringify({checks,stages:{exploration:B.Systems.Exploration.installedStages,locks:B.Systems.Locks.installedStages,crime:B.Systems.Crime.installedStages,property:B.Systems.Property.installedStages,fieldcraft:B.Systems.Fieldcraft.installedStages},fragments:{exploration:B.Systems.Exploration.installedFragments,crime:B.Systems.Crime.installedFragments,property:B.Systems.Property.installedFragments},oldErrors:a.__errs.slice(0,5),newErrors:b.__errs.slice(0,5)},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
