const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts,storage=new Map()){
  let ctx;
  function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},onclick:null};}
  const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};
  ctx=vm.createContext({console,Math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});
  ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};
  document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:'embedded-runtime.js'})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;
  for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}
  return ctx;
}
function norm(v,seen=new WeakSet()){if(typeof v==='function')return {$fn:String(v)};if(v===undefined)return {$undefined:true};if(v===null||typeof v!=='object')return v;if(seen.has(v))return {$cycle:true};seen.add(v);if(Array.isArray(v))return v.map(x=>norm(x,seen));if(v instanceof Set)return {$set:Array.from(v).map(x=>norm(x,seen))};const o={};for(const k of Object.keys(v).sort())o[k]=norm(v[k],seen);return o;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_10.js','js/dist/data_core_v11_10.js','tests/fixtures/base_main_v1118.js','js/legacy/compat_gameplay_config_trimmed_v1153.js','js/dist/canonical_v11_10.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_11.js','js/dist/data_core_v11_11.js','tests/fixtures/base_main_v1118.js','js/dist/systems_core_v11_11.js','js/legacy/compat_gameplay_systems_trimmed_v1153.js','js/dist/canonical_v11_11.js'];
const a=context(oldScripts),b=context(newScripts);const A=a.RF,B=b.RF;
function mk(R){let s=R.newGame('SystemParity','traveller','🥷');R.state=s;s.seed='system-parity';s.day=17;s.minute=720;s.location='greenvale';s.gold=99999;s.world=s.world||{};s.world.market={food:1.05,metal:.96,wood:1.08,general:1.02};s.inventory={...(s.inventory||{}),logs:5,raw_meat:3};s.stats=s.stats||{};s.stats.marketTrades=0;return s;}
const sa=mk(A),sb=mk(B);
const marketIds=Object.keys(A.V1054?.MARKETS||{}).sort();
const commerce={};let commerceSame=true;
for(const loc of marketIds){sa.location=loc;sb.location=loc;const ra=A.V1054.ensureStock(sa,loc),rb=B.V1054.ensureStock(sb,loc);const ids=Object.keys(ra?.stock||{}).sort();const rows=ids.map(id=>({id,stockA:ra.stock[id],stockB:rb.stock[id],buyA:A.V1054.buyPrice(sa,loc,id),buyB:B.V1054.buyPrice(sb,loc,id),sellA:A.V1054.sellPrice(sa,loc,id),sellB:B.V1054.sellPrice(sb,loc,id),maxA:A.V1054.buyMax(sa,loc,id),maxB:B.V1054.buyMax(sb,loc,id)}));commerce[loc]=rows;if(rows.some(x=>x.stockA!==x.stockB||x.buyA!==x.buyB||x.sellA!==x.sellB||x.maxA!==x.maxB))commerceSame=false;}
// Exercise a real trade mutation on both runtimes.
sa.location=sb.location='greenvale';A.UI.modal={type:'v1054Market'};B.UI.modal={type:'v1054Market'};A.V1054.ensureStock(sa,'greenvale');B.V1054.ensureStock(sb,'greenvale');
const tradeId=Object.keys(sa.v1054.markets.greenvale.stock)[0];A.V1054.trade('buy',tradeId,2);B.V1054.trade('buy',tradeId,2);
const tradeSame=JSON.stringify({gold:sa.gold,inv:sa.inventory[tradeId],stock:sa.v1054.markets.greenvale.stock[tradeId],trades:sa.stats.marketTrades})===JSON.stringify({gold:sb.gold,inv:sb.inventory[tradeId],stock:sb.v1054.markets.greenvale.stock[tradeId],trades:sb.stats.marketTrades});
const dungeonDataSame=JSON.stringify(norm(A.V1062?.DUNGEONS))===JSON.stringify(norm(B.V1062?.DUNGEONS));
const seq={};let seqSame=true;for(const loc of Object.keys(A.V1062?.DUNGEONS||{}).sort()){const x=A.V1062.sequence(sa,loc,3),y=B.V1062.sequence(sb,loc,3);seq[loc]={a:x,b:y};if(JSON.stringify(x)!==JSON.stringify(y))seqSame=false;}
const recA=A.V1062.record(sa,'old_mine'),recB=B.V1062.record(sb,'old_mine');const recordSame=JSON.stringify(recA)===JSON.stringify(recB);
const checks={version:B.VERSION==='11.11.0',schema:B.V95?.SCHEMA==='11.5.3',commerceCanonical:B.Modules?.info?.('systems.commerce')?.meta?.status==='canonical',dungeonsCanonical:B.Modules?.info?.('systems.dungeons')?.meta?.status==='canonical',commerceInstalled:B.Systems?.Commerce?.installed===true,dungeonsInstalled:B.Systems?.Dungeons?.installed===true,markets:Object.keys(B.V1054?.MARKETS||{}).length===10,dungeons:Object.keys(B.V1062?.DUNGEONS||{}).length===8,commerceSame,tradeSame,dungeonDataSame,seqSame,recordSame,ownership:B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true};
console.log(JSON.stringify({checks,marketIds,tradeId,sequenceSamples:seq,errors1110:a.__errs.slice(0,8),errors1111:b.__errs.slice(0,8)},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
