const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts,storage=new Map()){
  let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1};}
  const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};
  const math=Object.create(Math);math.random=()=>0.5;
  ctx=vm.createContext({console,Math:math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});
  ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};
  document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;
  for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}
  return ctx;
}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_16.js','js/dist/data_core_v11_16.js','tests/fixtures/base_main_v1118.js','js/dist/systems_core_v11_16.js','js/legacy/compat_gameplay_exploration_crime_property_trimmed_v1153.js','js/dist/canonical_v11_16.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_17.js','js/dist/data_core_v11_17.js','tests/fixtures/base_main_v1118.js','js/dist/systems_core_v11_17.js','js/legacy/compat_gameplay_time_energy_trimmed_v1153.js','js/dist/canonical_v11_17.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF;const same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function fresh(R,name='Parity'){
  const s=R.newGame(name,'traveller','🧭');R.state=s;s.day=5;s.minute=10*60;s.gold=5000;s.location='greenvale';s.player.level=20;s.player.maxEnergy=138;s.player.energy=120;s.speed=1;s.paused=false;
  for(const k of Object.keys(s.skills||{})){s.skills[k].level=20;s.skills[k].xp=R.xpForLevel?R.xpForLevel(20):s.skills[k].xp;}
  s.inventory={...(s.inventory||{}),lockpick:8,fine_lockpick:3,herb:8,wild_berries:8,raw_meat:8,bread:4,oak_logs:4};s.bank={...(s.bank||{}),raw_meat:8,herb:8};s.home=s.home||{};s.home.owned=true;s.stats=s.stats||{};R.UI.modal=null;R.actionGame=null;s.activity=null;
  if(R.V96){Object.assign(R.V96,{modalPaused:false,modalResume:null,selectPaused:false,selectResume:null,modalWasOpen:false,lastNonZeroSpeed:1});}
  return s;
}
const checks={};
// Pause / 1x / limited 2x and deliberate-manual-pause wrapper.
let sa=fresh(A,'OldSpeed'),sb=fresh(B,'NewSpeed');A.setSpeed(0);B.setSpeed(0);checks.pause=same({speed:sa.speed,paused:sa.paused,manual:sa.v83?.manualPause},{speed:sb.speed,paused:sb.paused,manual:sb.v83?.manualPause})&&sa.speed===0&&sa.paused===true;A.setSpeed(1);B.setSpeed(1);checks.speed1=same({speed:sa.speed,paused:sa.paused,manual:sa.v83?.manualPause},{speed:sb.speed,paused:sb.paused,manual:sb.v83?.manualPause})&&sa.speed===1&&!sa.paused;A.setSpeed(2);B.setSpeed(2);checks.speed2=sa.speed===2&&sb.speed===2&&!!sa.v8?.boostUntil&&!!sb.v8?.boostUntil&&sa.v83?.manualPause===sb.v83?.manualPause;
// Energy consumption and exact passive recovery.
sa=fresh(A,'OldEnergy'),sb=fresh(B,'NewEnergy');sa.player.energy=sb.player.energy=50;const spendA=A.v10SpendEnergy(sa,7),spendB=B.v10SpendEnergy(sb,7);checks.energySpend=spendA===spendB&&same({e:sa.player.energy,spent:sa.stats.energySpent},{e:sb.player.energy,spent:sb.stats.energySpent})&&sa.player.energy===43;
sa=fresh(A,'OldRecovery');sb=fresh(B,'NewRecovery');sa.player.energy=sb.player.energy=10;sa.v1023.energyRecoveryMinutes=sb.v1023.energyRecoveryMinutes=1;A.advanceWorld(8);B.advanceWorld(8);checks.energyRecovery=same({e:sa.player.energy,c:sa.v1023.energyRecoveryMinutes,day:sa.day,min:sa.minute},{e:sb.player.energy,c:sb.v1023.energyRecoveryMinutes,day:sb.day,min:sb.minute})&&sa.player.energy===13&&sa.v1023.energyRecoveryMinutes<0.0001;
// General world clock cadence and activity time-cost contract.
checks.clockCadence=A.V102.worldMinutesPerSecond===B.V102.worldMinutesPerSecond&&B.V102.worldMinutesPerSecond===0.8;sa=fresh(A,'OldActivity');sb=fresh(B,'NewActivity');A.startActivity('parity','Parity Activity',12,{tag:'x'});B.startActivity('parity','Parity Activity',12,{tag:'x'});checks.activityCost=same({type:sa.activity?.type,label:sa.activity?.label,duration:sa.activity?.duration,progress:sa.activity?.progress},{type:sb.activity?.type,label:sb.activity?.label,duration:sb.activity?.duration,progress:sb.activity?.progress})&&sa.activity.duration===12;
// Modal/background/select clock locking and restoration.
sa=fresh(A,'OldModal');sb=fresh(B,'NewModal');sa.speed=sb.speed=1;A.UI.modal={type:'message',title:'Parity',text:'Pause'};B.UI.modal={type:'message',title:'Parity',text:'Pause'};const needsA=A.v96ModalNeedsAutoPause(),needsB=B.v96ModalNeedsAutoPause();A.v96ApplyPause(sa,'modal');B.v96ApplyPause(sb,'modal');checks.modalLock=needsA===needsB&&needsA===true&&same({speed:sa.speed,paused:sa.paused,mp:A.V96.modalPaused},{speed:sb.speed,paused:sb.paused,mp:B.V96.modalPaused})&&sa.speed===0&&sa.paused;A.UI.modal=null;B.UI.modal=null;A.v96ReleasePause(sa,'modal');B.v96ReleasePause(sb,'modal');checks.modalRestore=same({speed:sa.speed,paused:sa.paused,mp:A.V96.modalPaused},{speed:sb.speed,paused:sb.paused,mp:B.V96.modalPaused})&&sa.speed===1&&!sa.paused;A.v96ApplyPause(sa,'select');B.v96ApplyPause(sb,'select');const selPause=same({speed:sa.speed,paused:sa.paused,sel:A.V96.selectPaused},{speed:sb.speed,paused:sb.paused,sel:B.V96.selectPaused});A.v96ReleasePause(sa,'select');B.v96ReleasePause(sb,'select');checks.selectLock=selPause&&same({speed:sa.speed,paused:sa.paused,sel:A.V96.selectPaused},{speed:sb.speed,paused:sb.paused,sel:B.V96.selectPaused});
// Combat clock capture/restore around a normal battle.
sa=fresh(A,'OldCombat');sb=fresh(B,'NewCombat');const enemyA=Object.keys(A.DATA.enemies||{})[0],enemyB=Object.keys(B.DATA.enemies||{})[0];A.startBattle(enemyA);B.startBattle(enemyB);const snapA=sa.combat?.v1026ResumeClock,snapB=sb.combat?.v1026ResumeClock;checks.combatCapture=!!sa.combat&&!!sb.combat&&same({speed:snapA?.speed,paused:snapA?.paused,from:sa.combat?.v1026FromTravel},{speed:snapB?.speed,paused:snapB?.paused,from:sb.combat?.v1026FromTravel});sa.combat=null;sb.combat=null;A.UI.modal=null;B.UI.modal=null;sa.speed=sb.speed=0;sa.paused=sb.paused=true;A.V1026.restoreClock(sa,snapA);B.V1026.restoreClock(sb,snapB);checks.combatRestore=same({speed:sa.speed,paused:sa.paused},{speed:sb.speed,paused:sb.paused})&&sa.speed===1;
// Travel start, progressive Energy accounting, and Travel-owned Clock Sentinel blockers.
sa=fresh(A,'OldTravel');sb=fresh(B,'NewTravel');const targetA=Object.keys(A.DATA.locations[sa.location].neighbors||{}).find(id=>A.V1022.locationUnlocked(sa,id));const targetB=targetA;const trA=A.travel(targetA),trB=B.travel(targetB);checks.travelStart=same({ret:!!trA,type:sa.activity?.type,target:sa.activity?.target,dur:sa.activity?.duration,total:sa.activity?.v1022EnergyTotal,spent:sa.activity?.v1022EnergySpent},{ret:!!trB,type:sb.activity?.type,target:sb.activity?.target,dur:sb.activity?.duration,total:sb.activity?.v1022EnergyTotal,spent:sb.activity?.v1022EnergySpent})&&sa.activity?.type==='travel';if(sa.activity&&sb.activity){sa.activity.progress=sb.activity.progress=3.2;sa.player.energy=sb.player.energy=100;sa.stats.travelEnergySpent=sb.stats.travelEnergySpent=0;A.advanceWorld(1);B.advanceWorld(1);}checks.travelEnergy=same({e:sa.player.energy,spent:sa.activity?.v1022EnergySpent,prog:sa.activity?.v1022EnergyProgress,stat:sa.stats.travelEnergySpent},{e:sb.player.energy,spent:sb.activity?.v1022EnergySpent,prog:sb.activity?.v1022EnergyProgress,stat:sb.stats.travelEnergySpent});
function sentinel(R,s){const V=R.V1122,out={run:V.trueBlocker(s)};R.UI.modal={type:'message'};out.modal=V.trueBlocker(s);R.UI.modal=null;s.combat={};out.combat=V.trueBlocker(s);s.combat=null;R.actionGame={type:'x'};out.action=V.trueBlocker(s);R.actionGame=null;s.speed=0;s.paused=true;out.paused=V.trueBlocker(s);return out;}
sa=fresh(A,'OldSentinel');sb=fresh(B,'NewSentinel');checks.clockSentinel=same(sentinel(A,sa),sentinel(B,sb))&&B.Systems.Travel.installedStages.includes('js/v11_2_2.js');
// Inn, home and campfire recovery.
sa=fresh(A,'OldInn');sb=fresh(B,'NewInn');for(const s of [sa,sb]){s.location='greenvale';s.player.hp=5;s.player.stamina=6;s.player.energy=7;s.minute=13*60;}A.v10RestUntil(7);B.v10RestUntil(7);checks.innRest=same({hp:sa.player.hp,st:sa.player.stamina,en:sa.player.energy,day:sa.day,min:sa.minute,r:sa.stats.innRests},{hp:sb.player.hp,st:sb.player.stamina,en:sb.player.energy,day:sb.day,min:sb.minute,r:sb.stats.innRests});
sa=fresh(A,'OldHome');sb=fresh(B,'NewHome');for(const s of [sa,sb]){s.location='greenvale';s.home.owned=true;s.player.hp=12;s.player.stamina=13;s.player.energy=14;}A.restAtHome();B.restAtHome();checks.homeRest=same({hp:sa.player.hp,st:sa.player.stamina,en:sa.player.energy,wr:sa.home.wellRestedBattles,day:sa.day,min:sa.minute},{hp:sb.player.hp,st:sb.player.stamina,en:sb.player.energy,wr:sb.home.wellRestedBattles,day:sb.day,min:sb.minute});
sa=fresh(A,'OldCamp');sb=fresh(B,'NewCamp');for(const [R,s] of [[A,sa],[B,sb]]){s.location='forest';s.camp={location:'forest',expiresAt:R.totalMinutes(s)+1000,quality:1};s.player.hp=20;s.player.stamina=20;s.player.energy=20;}A.restByFire();B.restByFire();checks.campRest=same({hp:sa.player.hp,st:sa.player.stamina,en:sa.player.energy,day:sa.day,min:sa.minute},{hp:sb.player.hp,st:sb.player.stamina,en:sb.player.energy,day:sb.day,min:sb.minute});
// Explore, excavation, pickpocket, burglary/cooldowns, Property UI.
sa=fresh(A,'OldExplore');sb=fresh(B,'NewExplore');sa.location=sb.location='ruins';A.action('explore');B.action('explore');checks.explore=same({a:sa.activity&&{type:sa.activity.type,duration:sa.activity.duration,progress:sa.activity.progress},e:sa.player.energy},{a:sb.activity&&{type:sb.activity.type,duration:sb.activity.duration,progress:sb.activity.progress},e:sb.player.energy});
sa=fresh(A,'OldDig');sb=fresh(B,'NewDig');sa.location=sb.location='ruins';A.startExcavation('ruins');B.startExcavation('ruins');checks.excavation=same({type:A.actionGame?.type,secret:A.actionGame?.secret,digs:A.actionGame?.digs},{type:B.actionGame?.type,secret:B.actionGame?.secret,digs:B.actionGame?.digs});
sa=fresh(A,'OldCrime');sb=fresh(B,'NewCrime');A.startPickpocket('mira',false);B.startPickpocket('mira',false);checks.pickpocket=same({type:A.actionGame?.type,id:A.actionGame?.id,target:A.actionGame?.target,width:A.actionGame?.width,vig:A.actionGame?.vigilance},{type:B.actionGame?.type,id:B.actionGame?.id,target:B.actionGame?.target,width:B.actionGame?.width,vig:B.actionGame?.vigilance});
sa=fresh(A,'OldBurg');sb=fresh(B,'NewBurg');const siteA=A.v92BurglarySites.greenvale[0],siteB=B.v92BurglarySites.greenvale[0];A.v92ChooseBurglary(siteA.id);B.v92ChooseBurglary(siteB.id);A.V1031.setCooldown(sa,siteA,true);B.V1031.setCooldown(sb,siteB,true);checks.burglary=same({modal:A.UI.modal?.type,id:A.UI.modal?.site?.id,cd:A.V1031.cooldownRemaining(sa,siteA)},{modal:B.UI.modal?.type,id:B.UI.modal?.site?.id,cd:B.V1031.cooldownRemaining(sb,siteB)})&&A.V1031.cooldownRemaining(sa,siteA)===1440;
sa=fresh(A,'OldPropertyUI');sb=fresh(B,'NewPropertyUI');checks.propertyUI=norm(A.V1024.homePanel(sa))===norm(B.V1024.homePanel(sb))&&A.v10InnHere(sa)===B.v10InnHere(sb);
// Over-encumbrance remains Inventory-owned and blocks time/travel losslessly.
function overload(R,s,prefix){for(let i=0;i<R.packCapacity(s)+3;i++){const id=prefix+i;R.DATA.items[id]={name:id,icon:'•',type:'material',value:1};s.inventory[id]=1;}R.V1056.enforcePause(s,{log:false});return {over:R.V1056.isOver(s),ex:R.packExcess(s),speed:s.speed,paused:s.paused};}
sa=fresh(A,'OldOver');sb=fresh(B,'NewOver');const oa=overload(A,sa,'olda_'),ob=overload(B,sb,'newb_');const beforeMinA=sa.minute,beforeMinB=sb.minute;A.advanceWorld(10);B.advanceWorld(10);A.setSpeed(1);B.setSpeed(1);checks.overEncumbrance=oa.over&&ob.over&&oa.ex===ob.ex&&sa.minute===beforeMinA&&sb.minute===beforeMinB&&sa.speed===0&&sb.speed===0;
// Architecture ownership assertions.
checks.timeEnergyCanonical=B.Modules?.info?.('systems.timeEnergy')?.meta?.status==='canonical'&&B.Systems.TimeEnergy.installedStages.length===2&&B.Systems.TimeEnergy.installedFragments.length===5;
checks.focusClockCanonical=B.Modules?.info?.('ui.focusClock')?.meta?.status==='canonical'&&B.Views.FocusClock.installedStages.includes('js/v9_6.js');
checks.gatheringFragment=B.Systems.Gathering.installedFragments.includes('v10_22-continuous-gathering');
checks.crimeGlue=B.Systems.Crime.installedFragments.includes('v10_2-pickpocket-feedback')&&B.Systems.Crime.installedFragments.includes('v10_2-pickpocket-ui');
checks.travelOwnsSentinel=B.Systems.Travel.installedStages.includes('js/v11_2_2.js');
checks.propertyOwnsRest=B.Systems.Property.installedStages.includes('js/v10_24.js')&&B.Systems.Property.installedFragments.includes('v10-inn-rest');
checks.ownership=B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true;
checks.schema=B.V95?.SCHEMA==='11.5.3';checks.version=B.VERSION==='11.17.0';
const errorsEquivalent=a.__errs.length===b.__errs.length&&a.__errs.map(x=>String(x).includes('modalHTML')).every(Boolean)&&b.__errs.map(x=>String(x).includes('modalHTML')).every(Boolean);checks.knownHarnessWarningEquivalent=errorsEquivalent;
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,3),newErrors:b.__errs.slice(0,3),owners:{timeEnergy:B.Systems.TimeEnergy.installedFragments,focus:B.Views.FocusClock.installedStages,gathering:B.Systems.Gathering.installedFragments,crime:B.Systems.Crime.installedFragments.slice(-3),travel:B.Systems.Travel.installedStages}},null,2));
if(Object.values(checks).some(v=>!v))process.exit(2);
