const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts,storage=new Map()){
  let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},onclick:null,offsetWidth:1};}
  const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};
  const math=Object.create(Math);math.random=()=>0.5;
  ctx=vm.createContext({console,Math:math,Date,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/'},history:{pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});
  ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};
  document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:'embedded-runtime.js'})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;
  for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}
  return ctx;
}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_14.js','js/dist/data_core_v11_14.js','js/legacy/base/main.js','js/dist/systems_core_v11_14.js','js/legacy/compat_gameplay_research_skills_trimmed_v1153.js','js/dist/canonical_v11_14.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_15.js','js/dist/data_core_v11_15.js','js/legacy/base/main.js','js/dist/systems_core_v11_15.js','js/legacy/compat_gameplay_fieldcraft_trimmed_v1153.js','js/dist/canonical_v11_15.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF;const same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function mk(R,name){let s=R.newGame(name,'traveller','🧭');R.state=s;s.seed='v1115-parity';s.day=3;s.minute=9*60;s.gold=5000;s.player.energy=s.player.maxEnergy||100;for(const k of Object.keys(s.skills||{})){s.skills[k].level=20;s.skills[k].xp=R.xpForLevel?R.xpForLevel(20):s.skills[k].xp;}s.inventory={...(s.inventory||{}),steel_pickaxe:1,steel_axe:1,angler_rod:1,tinderbox:1,trout:4,raw_meat:6,herb:6,wild_berries:8,logs:8};s.toolbelt={...(s.toolbelt||{}),mining:'steel_pickaxe',woodcutting:'steel_axe',fishing:'angler_rod',firemaking:'tinderbox'};s.bank={raw_meat:10,herb:10,wild_berries:10};s.home=s.home||{};s.home.owned=true;s.stats=s.stats||{};s.v7=s.v7||{};s.v7.rareFinds=s.v7.rareFinds||0;s.v7.formulas=s.v7.formulas||{};R.UI.modal=null;return s;}
const sa=mk(A,'FieldcraftOld'),sb=mk(B,'FieldcraftNew');
// Static resource/camp definitions and best-tool resolution.
const resourceDefsSame=same(A.DATA.resourceDefs,B.DATA.resourceDefs),locationResourcesSame=same(A.DATA.locationResources,B.DATA.locationResources),campRecipesSame=same(A.DATA.campRecipes,B.DATA.campRecipes);
const toolSame=same(A.bestTool(sa,'mining'),B.bestTool(sb,'mining'))&&A.bestTool(sa,'mining')?.id==='steel_pickaxe';
// Active gathering parity.
sa.location=sb.location='forest';A.startGather('oak');B.startGather('oak');const gatherStartSame=same({type:A.actionGame?.type,key:A.actionGame?.key,progress:A.actionGame?.progress},{type:B.actionGame?.type,key:B.actionGame?.key,progress:B.actionGame?.progress});
for(let i=0;i<5&&A.actionGame;i++)A.workTap();for(let i=0;i<5&&B.actionGame;i++)B.workTap();
const gatherFinishSame=same({logs:sa.inventory.logs,xp:sa.skills.woodcutting.xp,level:sa.skills.woodcutting.level,charges:A.resourceState(sa,'oak').charges,stats:sa.stats.resourcesGathered},{logs:sb.inventory.logs,xp:sb.skills.woodcutting.xp,level:sb.skills.woodcutting.level,charges:B.resourceState(sb,'oak').charges,stats:sb.stats.resourcesGathered});
// Fishing parity, forcing a bite without relying on timers.
sa.location=sb.location='river';A.startGather('trout');B.startGather('trout');A.actionGame.stage='bite';B.actionGame.stage='bite';A.actionGame.biteAt=Date.now()+1000;B.actionGame.biteAt=Date.now()+1000;A.actionGame.window=3000;B.actionGame.window=3000;A.reelFish();B.reelFish();
const fishingSame=same({trout:sa.inventory.trout,xp:sa.skills.fishing.xp,escaped:sa.stats.fishEscaped,broken:sa.stats.linesBroken},{trout:sb.inventory.trout,xp:sb.skills.fishing.xp,escaped:sb.stats.fishEscaped,broken:sb.stats.linesBroken});
// Hunting parity, forcing the final opening without timer execution.
A.startHunt();B.startHunt();A.actionGame.stage='strike';B.actionGame.stage='strike';A.actionGame.strikeAt=Date.now();B.actionGame.strikeAt=Date.now();A.huntStrike();B.huntStrike();
const huntingSame=same({meat:sa.inventory.raw_meat,pelt:sa.inventory.wolf_pelt||0,xp:sa.skills.hunting.xp},{meat:sb.inventory.raw_meat,pelt:sb.inventory.wolf_pelt||0,xp:sb.skills.hunting.xp});
// Camp cooking parity. Force the marker to the centre of the sweet spot.
sa.location=sb.location='forest';sa.camp={location:'forest',expiresAt:A.totalMinutes(sa)+200,quality:2};sb.camp={location:'forest',expiresAt:B.totalMinutes(sb)+200,quality:2};A.cookAtFire('cooked_trout');B.cookAtFire('cooked_trout');A.actionGame.target=A.cookPosition(A.actionGame);B.actionGame.target=B.cookPosition(B.actionGame);A.turnCook();B.turnCook();
const cookingSame=same({trout:sa.inventory.trout,cooked:sa.inventory.cooked_trout||0,xp:sa.skills.cooking.xp,meals:sa.stats.mealsCooked,perfect:sa.stats.perfectCooks},{trout:sb.inventory.trout,cooked:sb.inventory.cooked_trout||0,xp:sb.skills.cooking.xp,meals:sb.stats.mealsCooked,perfect:sb.stats.perfectCooks});
// V7 rare-skilling fragment parity.
a.Math.random=()=>0.01;b.Math.random=()=>0.01;const rareA=A.v7RareSkillFind(sa,'fishing'),rareB=B.v7RareSkillFind(sb,'fishing');const rareSame=rareA===rareB&&rareA==='mire_pearl'&&sa.v7.rareFinds===sb.v7.rareFinds;
a.Math.random=()=>0.5;b.Math.random=()=>0.5;
// V10.24 home-kitchen parity, including Pack+Bank ingredient accounting.
sa.location=sb.location='greenvale';sa.home.owned=sb.home.owned=true;sa.inventory.raw_meat=sb.inventory.raw_meat=0;sa.inventory.herb=sb.inventory.herb=0;sa.bank.raw_meat=sb.bank.raw_meat=10;sa.bank.herb=sb.bank.herb=10;
const homeNeedsSame=same(A.V1024.recipeNeeds(A.DATA.campRecipes.venison_stew),B.V1024.recipeNeeds(B.DATA.campRecipes.venison_stew))&&A.V1024.hasIngredients(sa,A.DATA.campRecipes.venison_stew,'home')===B.V1024.hasIngredients(sb,B.DATA.campRecipes.venison_stew,'home');
A.V1024.startHomeCook('venison_stew');B.V1024.startHomeCook('venison_stew');A.actionGame.target=A.cookPosition(A.actionGame);B.actionGame.target=B.cookPosition(B.actionGame);A.turnCook();B.turnCook();
const homeCookSame=same({out:sa.inventory.venison_stew||0,bankMeat:sa.bank.raw_meat||0,bankHerb:sa.bank.herb||0,xp:sa.skills.cooking.xp},{out:sb.inventory.venison_stew||0,bankMeat:sb.bank.raw_meat||0,bankHerb:sb.bank.herb||0,xp:sb.skills.cooking.xp});
const homePanelSame=norm(A.V1024.homePanel(sa))===norm(B.V1024.homePanel(sb));
const checks={version:B.VERSION==='11.15.0',schema:B.V95?.SCHEMA==='11.5.3',resourceDefsSame,locationResourcesSame,campRecipesSame,toolSame,gatherStartSame,gatherFinishSame,fishingSame,huntingSame,cookingSame,rareSame,homeNeedsSame,homeCookSame,homePanelSame,
 fieldcraftCanonical:B.Modules?.info?.('systems.fieldcraft')?.meta?.status==='canonical'&&B.Systems.Fieldcraft.installedStages.length===3&&B.Systems.Fieldcraft.installedFragments.length===3,
 gatheringCanonical:B.Modules?.info?.('systems.gathering')?.meta?.status==='canonical',huntingCanonical:B.Modules?.info?.('systems.hunting')?.meta?.status==='canonical',fishingCanonical:B.Modules?.info?.('systems.fishing')?.meta?.status==='canonical',cookingCanonical:B.Modules?.info?.('systems.cooking')?.meta?.status==='canonical',ownership:B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true};
console.log(JSON.stringify({checks,stages:B.Systems.Fieldcraft.installedStages,fragments:B.Systems.Fieldcraft.installedFragments,oldErrors:a.__errs.slice(0,5),newErrors:b.__errs.slice(0,5)},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
