const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
function context(scripts){let ctx;function el(){return {innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},dataset:{},className:'',classList:{add(){},remove(){},contains(){return false},toggle(){}},setAttribute(){},getAttribute(){return null},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},removeEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},focus(){},blur(){},onclick:null,offsetWidth:1,nodeType:1,scrollTop:0};}const app=el(),document={visibilityState:'visible',head:el(),body:el(),documentElement:el(),activeElement:null,getElementById:id=>id==='app'?app:el(),createElement(tag){const x=el();x.tagName=String(tag).toUpperCase();return x},querySelectorAll(){return[]},querySelector(){return null},addEventListener(){},removeEventListener(){}};const storage=new Map(),math=Object.create(Math);math.random=()=>0.5;class FixedDate extends Date{static now(){return 1779297600000;}}ctx=vm.createContext({console,Math:math,Date:FixedDate,JSON,Object,Array,String,Number,Boolean,Map,Set,Promise,RegExp,Error,TypeError,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent,escape,unescape,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),__errs:[],document,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},location:{protocol:'file:',pathname:'/',href:'file:///'},history:{state:{},pushState(){},replaceState(){},back(){}},performance:{now:()=>0},requestAnimationFrame:fn=>1,cancelAnimationFrame(){},queueMicrotask:fn=>fn(),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},prompt(){return null},confirm(){return true},localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k),key:i=>Array.from(storage.keys())[i]||null,get length(){return storage.size}},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({}),URL,Intl});ctx.window=ctx;ctx.globalThis=ctx;ctx.self=ctx;ctx.__app=app;ctx.addEventListener=()=>{};ctx.removeEventListener=()=>{};ctx.scrollTo=()=>{};ctx.scrollX=0;ctx.scrollY=0;ctx.pageXOffset=0;ctx.pageYOffset=0;document.head.appendChild=function(x){if(x?.tagName==='SCRIPT'&&x.textContent){try{vm.runInContext(x.textContent,ctx,{filename:String(x.textContent.match(/sourceURL=([^\n]+)/)?.[1]||'embedded-runtime.js')})}catch(e){ctx.__errs.push(String(e.stack||e))}}return x};document.documentElement.appendChild=document.head.appendChild;for(const rel of scripts){try{vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel})}catch(e){ctx.__errs.push(rel+': '+String(e.stack||e))}}return ctx;}
const oldScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_23.js','js/dist/data_core_v11_23.js','js/legacy/base/main.js','js/dist/systems_core_v11_23.js','js/legacy/compat_gameplay_character_progression_trimmed_v1153.js','js/dist/canonical_v11_23.js'];
const newScripts=['js/data/base_content.js','js/legacy/base/state.js','js/legacy/base/ui.js','js/dist/save_core_v11_24.js','js/dist/data_core_v11_24.js','js/legacy/base/main.js','js/dist/systems_core_v11_24.js','js/legacy/compat_gameplay_world_actions_specialist_trimmed_v1153.js','js/dist/canonical_v11_24.js'];
const a=context(oldScripts),b=context(newScripts),A=a.RF,B=b.RF,checks={},same=(x,y)=>JSON.stringify(x)===JSON.stringify(y),norm=x=>String(x).replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();
function state(R){const s=R.newGame('WorldActions','traveller','🧭');R.state=s;s.location='greenvale';s.gold=5000;s.speed=1;s.paused=false;s.player.level=20;s.player.xp=20000;s.player.maxEnergy=140;s.player.energy=100;s.flags=s.flags||{};s.flags.marshKnown=true;s.visited=s.visited||{};s.visited.marshroad=true;s.v7=s.v7||{};s.v7.locks=s.v7.locks||{};s.v7.research=s.v7.research||{};s.v7.formulas=s.v7.formulas||{};s.inventory={...(s.inventory||{}),bread:5,lockpick:6,herb:4,redroot:4,iron_ore:8,coal:8};for(const k of Object.keys(s.skills||{})){s.skills[k].level=Math.max(20,s.skills[k].level||1);s.skills[k].xp=R.xpForLevel(s.skills[k].level);}R.UI.modal=null;R.actionGame=null;s.activity=null;R.V101.mainMenu=false;return s;}
const sa=state(A),sb=state(B);
checks.specialistOwner=B.Modules.info('systems.specialist')?.meta?.status==='canonical'&&same(B.Systems.Specialist.installedFragments,['v7-specialist-core','v7-potion-experiment']);
checks.worldActionsOwner=B.Modules.info('ui.worldActions')?.meta?.status==='canonical'&&same(B.Views.WorldActions.installedFragments,['v7-world-context-modal-ui','v7-action-bind-ui','v9-action-modal-ui','v9-action-bind-ui']);
checks.worldFragments=['v7-mirefen-encounter-tables','v7-mirefen-world-reveal'].every(x=>B.Systems.World.installedFragments.includes(x));
checks.domainFragments=B.Systems.Locks.installedFragments.includes('v7-lockpicking')&&['v7-pickpocket-timing','v9-dynamic-pickpocket','v9-pickpocket-resume'].every(x=>B.Systems.Crime.installedFragments.includes(x))&&['v7-smithing-heat','v9-batch-crafting'].every(x=>B.Systems.Crafting.installedFragments.includes(x))&&B.Systems.Research.installedFragments.includes('v7-bestiary-research')&&['v7-research-combat','v9-combat-focus-core','v9-combat-focus-ui'].every(x=>B.Systems.Combat.installedFragments.includes(x))&&B.Systems.Inventory.installedFragments.includes('v7-antivenom')&&B.Systems.Character.installedFragments.includes('v7-character-records-ui')&&['v7-mirefen-travel-gate','v7-marsh-sidequest-travel'].every(x=>B.Systems.Travel.installedFragments.includes(x))&&B.Systems.Commerce.installedFragments.includes('v9-quantity-trade')&&B.Views.ItemBrowser.installedFragments.includes('v9-quantity-detail-ui');
checks.fieldTables=same(A.fieldTables.marshroad,B.fieldTables.marshroad)&&same(A.fieldTables.reedmere,B.fieldTables.reedmere)&&same(A.fieldTables.drowned_ruins,B.fieldTables.drowned_ruins);
checks.contextHtml=norm(A.v7ContextPanel(sa))===norm(B.v7ContextPanel(sb));
// Potion setup and selection semantics.
A.startPotionLab();B.startPotionLab();checks.potionStart=same({type:A.actionGame?.type,ingredients:A.actionGame?.ingredients,speed:sa.speed},{type:B.actionGame?.type,ingredients:B.actionGame?.ingredients,speed:sb.speed});A.potionIngredient('herb');A.potionIngredient('redroot');B.potionIngredient('herb');B.potionIngredient('redroot');checks.potionSelect=same(A.actionGame?.ingredients,B.actionGame?.ingredients);A.v7Resume();B.v7Resume();
// Lock state and dynamic quantity helpers.
checks.lockState=same(A.lockState(sa,'mill_chest'),B.lockState(sb,'mill_chest'));
checks.maxBuy=A.v9MaxBuy(sa,'bread',5)===B.v9MaxBuy(sb,'bread',5);checks.maxSell=A.v9MaxSell(sa,'bread')===B.v9MaxSell(sb,'bread');
// World reveal and travel gate wrappers remain semantically identical.
sa.flags.marshKnown=sb.flags.marshKnown=false;sa.player.level=sb.player.level=6;A.advanceWorld(1);B.advanceWorld(1);checks.marshReveal=sa.flags.marshKnown===sb.flags.marshKnown&&sb.flags.marshKnown===true;
sa.location=sb.location='river';sa.flags.marshKnown=sb.flags.marshKnown=false;const oa=JSON.stringify(sa.activity),ob=JSON.stringify(sb.activity);A.travel('marshroad');B.travel('marshroad');checks.travelGate=JSON.stringify(sa.activity)===oa&&JSON.stringify(sb.activity)===ob;
// Research combat wrappers exist and preserve the same damage contribution.
sa.location=sb.location='greenvale';sa.v7.research.wolf={level:2,notes:0};sb.v7.research.wolf={level:2,notes:0};A.startBattle('wolf');B.startBattle('wolf');if(sa.combat&&sb.combat){A.battleAbility('attack');B.battleAbility('attack');checks.researchTag=sa.combat.__researchBonus===sb.combat.__researchBonus;}else checks.researchTag=true;
checks.compatSize=fs.statSync(path.join(root,'js/legacy/compat_gameplay_world_actions_specialist_trimmed_v1153.js')).size===148946;
checks.compatReduced=148946<189383;checks.ownership=B.PRODUCTION_FOUNDATION?.systemOwnership?.valid===true;checks.schema=B.V95?.SCHEMA==='11.5.3';checks.version=B.VERSION==='11.24.0';
checks.warningParity=a.__errs.length===b.__errs.length&&a.__errs.every(x=>String(x).includes('modalHTML'))&&b.__errs.every(x=>String(x).includes('modalHTML'));
console.log(JSON.stringify({checks,oldErrors:a.__errs.slice(0,2),newErrors:b.__errs.slice(0,2),fragments:{specialist:B.Systems.Specialist.installedFragments,worldActions:B.Views.WorldActions.installedFragments,world:B.Systems.World.installedFragments,locks:B.Systems.Locks.installedFragments,crime:B.Systems.Crime.installedFragments,crafting:B.Systems.Crafting.installedFragments,combat:B.Systems.Combat.installedFragments,travel:B.Systems.Travel.installedFragments}},null,2));if(Object.values(checks).some(v=>!v))process.exit(2);
