window.RF = window.RF || {};
RF.UI = {
  tab:'world', modal:null,
  fmtTime(s){let h=Math.floor(s.minute/60)%24,m=Math.floor(s.minute%60);return `Day ${s.day} • ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`},
  render(s){
    const root=document.getElementById('app');
    if(!s){root.innerHTML=this.creator();this.bindCreator();return;}
    root.innerHTML=`<div class="app">${this.top(s)}<main class="content">${this.page(s)}</main>${this.nav()}</div>${this.modal?this.modalHtml(s):''}`;
    this.bind(s);
  },
  creator(){const bgs=Object.entries(RF.DATA.backgrounds).map(([id,b],i)=>`<button class="bgopt ${i===0?'sel':''}" data-bg="${id}"><b>${b.icon} ${b.name}</b><small>${b.desc}</small></button>`).join('');return `<div class="creator"><div class="logo">REALMFORGE<small>WANDERER'S RISE</small></div><div class="creatorCard"><h2 style="font-family:Georgia,serif;color:#f0d398;margin-top:0">Create your wanderer</h2><div class="field"><label>Name</label><input id="charName" maxlength="18" value="Angus" /></div><div class="field"><label>Avatar</label><select id="avatar"><option>🧑</option><option>🧔</option><option>👩</option><option>🧝</option><option>🧙</option><option>🥷</option></select></div><div class="field"><label>Background</label><div class="backgrounds">${bgs}</div></div><button id="startGame" class="startBtn">Begin the Journey</button><div class="sub center" style="margin-top:10px">Your background gives a small head start. It never locks your build.</div></div></div>`},
  bindCreator(){let chosen='farmer';document.querySelectorAll('.bgopt').forEach(x=>x.onclick=()=>{document.querySelectorAll('.bgopt').forEach(y=>y.classList.remove('sel'));x.classList.add('sel');chosen=x.dataset.bg});document.getElementById('startGame').onclick=()=>RF.startNew(document.getElementById('charName').value.trim(),chosen,document.getElementById('avatar').value)},
  top(s){let hp=100*s.player.hp/s.player.maxHp,st=100*s.player.stamina/s.player.maxStamina;return `<header class="topbar"><div class="heroRow"><div class="avatar">${s.player.avatar}</div><div class="grow"><div class="nameLine"><strong>${s.player.name}</strong><span class="tiny">Lv ${s.player.level} • ${s.gold}g</span></div><div class="tiny">HP ${Math.ceil(s.player.hp)}/${s.player.maxHp}</div><div class="bar"><div class="fill hp" style="width:${hp}%"></div></div><div class="tiny" style="margin-top:3px">Stamina ${Math.ceil(s.player.stamina)}/${s.player.maxStamina}</div><div class="bar"><div class="fill st" style="width:${st}%"></div></div></div></div><div class="timeRow"><div class="clock">${this.fmtTime(s)} • ${s.weather}</div><div class="speeds">${[0,1,2,3,4].map(v=>`<button class="speed ${s.speed===v?'active':''}" data-speed="${v}">${v===0?'Ⅱ':v+'×'}</button>`).join('')}</div></div></header>`},
  nav(){let n=[['world','🌍','WORLD'],['character','🧍','CHAR'],['skills','📊','SKILLS'],['inventory','🎒','PACK'],['quests','📜','QUESTS'],['shop','🪙','SHOP']];return `<nav class="bottomnav"><div class="bottomInner">${n.map(x=>`<button class="navbtn ${this.tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div></nav>`},
  page(s){if(this.tab==='world')return this.world(s);if(this.tab==='character')return this.character(s);if(this.tab==='skills')return this.skills(s);if(this.tab==='inventory')return this.inventory(s);if(this.tab==='quests')return this.quests(s);return this.shop(s)},
  world(s){const l=RF.DATA.locations[s.location],hour=Math.floor(s.minute/60)%24,night=hour<6||hour>=20;let travel=Object.entries(l.neighbors||{}).filter(([id])=>{let x=RF.DATA.locations[id];if(x.lockedFlag&&!s.flags[x.lockedFlag])return false;if(x.lockedSkill){let [sk,lv]=Object.entries(x.lockedSkill)[0];if(s.skills[sk].level<lv)return false}return true}).map(([id,min])=>`<button class="action" data-travel="${id}"><span class="emoji">${RF.DATA.locations[id].icon}</span><b>${RF.DATA.locations[id].name}</b><small>${min} min travel</small></button>`).join('');let actions=(l.actions||[]).map(a=>this.actionButton(a,s)).join('');return `<div class="scene"><div class="sun ${night?'moon':''}"></div><div class="weather">${this.weatherIcon(s.weather)} ${s.weather}</div><div class="sceneText"><strong>${l.icon} ${l.name}</strong><div class="sub">${l.desc}</div></div></div>${s.combat?this.combat(s):''}${s.activity?this.activity(s):''}<section class="card"><h3>Actions</h3><div class="grid2">${actions}</div></section><section class="card"><h3>Travel</h3><div class="grid2">${travel||'<div class="sub">No roads from here.</div>'}</div></section><section class="card"><h3>World Feed</h3><div class="log">${s.log.map(x=>`<div class="${x.type}"><span>${x.t}</span> ${x.text}</div>`).join('')}</div></section>`},
  weatherIcon(w){return ({Clear:'☀️',Rain:'🌧️',Fog:'🌫️',Storm:'⛈️',Cloudy:'☁️'})[w]||'☀️'},
  actionButton(a,s){const map={rest:['🛏️','Rest','Recover health & stamina'],forage:['🌿','Forage','Find herbs and food'],talk:['💬','Talk Around','Hear rumours'],woodcut:['🪓','Chop Wood','Train Woodcutting'],hunt:['🐾','Hunt','Track local game'],fish:['🎣','Fish','Catch riverfish'],mine:['⛏️','Mine','Gather ore'],explore:['🧭','Explore','Search for secrets'],wait:['⏳','Wait','Let the road come to you']};let x=map[a];return `<button class="action ${a==='explore'?'primary':''}" data-action="${a}" ${s.activity||s.combat?'disabled':''}><span class="emoji">${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`},
  activity(s){let a=s.activity,p=Math.min(100,100*a.progress/a.duration);return `<div class="card"><div class="progressTitle"><b>${a.label}</b><span>${Math.floor(p)}%</span></div><div class="progressOuter"><div class="progressInner" style="width:${p}%"></div></div><button class="cancelBtn" data-cancel>Cancel activity</button></div>`},
  combat(s){let e=s.combat,enemy=RF.DATA.enemies[e.id];return `<div class="card"><h3>Combat</h3><div class="combatant"><div class="combatIcon">${enemy.icon}</div><div class="grow"><b>${enemy.name} • Lv ${enemy.level}</b><div class="tiny">HP ${Math.max(0,Math.ceil(e.hp))}/${enemy.hp}</div><div class="bar"><div class="fill hp" style="width:${100*e.hp/enemy.hp}%"></div></div></div></div><div class="combatBtns"><button class="action primary" data-combat="attack"><b>⚔️ Attack</b><small>Reliable strike</small></button><button class="action" data-combat="heavy"><b>🪓 Heavy</b><small>Harder, less accurate</small></button><button class="action" data-combat="defend"><b>🛡️ Defend</b><small>Reduce next hit</small></button><button class="action danger" data-combat="flee"><b>🏃 Flee</b><small>Attempt escape</small></button></div></div>`},
  character(s){let bg=RF.DATA.backgrounds[s.player.background];return `<section class="card"><h2>${s.player.avatar} ${s.player.name}</h2><div class="sub">${bg.icon} ${bg.name} • Character Level ${s.player.level}</div><hr><div class="statsGrid"><div class="statbox"><span>Health</span><b>${s.player.hp}/${s.player.maxHp}</b></div><div class="statbox"><span>Stamina</span><b>${Math.ceil(s.player.stamina)}/${s.player.maxStamina}</b></div><div class="statbox"><span>Armour</span><b>${RF.armor(s)}</b></div><div class="statbox"><span>Weapon Damage</span><b>${RF.weaponDamage(s)}</b></div><div class="statbox"><span>Greenvale Rep</span><b>${s.reputation.greenvale}</b></div><div class="statbox"><span>Luck</span><b>${s.luck||0}</b></div></div></section><section class="card"><h3>Equipment</h3><div class="list">${['main','head','chest'].map(slot=>{let id=s.equipment[slot],it=id?RF.DATA.items[id]:null;return `<div class="row"><div class="icon">${it?.icon||'▫️'}</div><div class="meta"><b>${slot.toUpperCase()}</b><small>${it?.name||'Empty slot'}</small></div></div>`}).join('')}</div></section><section class="card"><h3>Lifetime</h3><div class="statsGrid"><div class="statbox"><span>Enemies defeated</span><b>${s.stats.enemiesKilled}</b></div><div class="statbox"><span>Items crafted</span><b>${s.stats.itemsCrafted}</b></div><div class="statbox"><span>Distance travelled</span><b>${s.stats.distance} min</b></div><div class="statbox"><span>Play time</span><b>${Math.floor(s.stats.playMinutes/60)}h ${s.stats.playMinutes%60}m</b></div></div><hr><div class="grid2"><button class="action" data-export><b>💾 Export Save</b><small>Copy backup text</small></button><button class="action" data-import><b>📥 Import Save</b><small>Restore backup</small></button></div></section>`},
  skills(s){return `<section class="card"><h2>Skills</h2><div class="sub">Skills improve by doing. Level cap: 100.</div><div class="list" style="margin-top:10px">${Object.entries(RF.DATA.skills).map(([id,d])=>{let sk=s.skills[id],next=RF.xpForLevel(Math.min(100,sk.level+1)),prev=RF.xpForLevel(sk.level),p=sk.level>=100?100:100*(sk.xp-prev)/(next-prev);return `<div class="row skill"><div class="skillIcon">${d.icon}</div><div><div class="skillName">${d.name}</div><div class="miniBar"><div class="miniFill" style="width:${Math.max(0,Math.min(100,p))}%"></div></div><small>${sk.xp} XP</small></div><div class="skillLevel">${sk.level}</div></div>`}).join('')}</div></section><section class="card"><h3>Crafting</h3><div class="list">${Object.entries(RF.DATA.recipes).map(([id,r])=>{let can=s.skills[r.skill].level>=r.level&&RF.hasItems(s,r.inputs);return `<div class="row"><div class="icon">${RF.DATA.items[id].icon}</div><div class="meta"><b>${r.name}</b><small>${r.skill} Lv ${r.level} • ${Object.entries(r.inputs).map(([x,q])=>`${q}× ${RF.DATA.items[x].name}`).join(', ')}</small></div><button data-craft="${id}" ${can?'':'disabled'}>Craft</button></div>`}).join('')}</div></section>`},
  inventory(s){let rows=Object.entries(s.inventory).map(([id,q])=>{let it=RF.DATA.items[id];if(!it)return'';let equip=it.slot?`<button data-equip="${id}">Equip</button>`:'';let use=(it.heal||it.stamina)?`<button data-use="${id}">Use</button>`:'';return `<div class="row"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>${it.desc}</small></div><span class="qty">×${q}</span>${equip||use}</div>`}).join('');return `<section class="card"><h2>Inventory</h2><div class="sub">${Object.values(s.inventory).reduce((a,b)=>a+b,0)} carried items</div><div class="list" style="margin-top:10px">${rows||'<div class="sub">Your pack is empty.</div>'}</div></section>`},
  quests(s){return `<section class="card"><h2>Quest Journal</h2><div class="list">${Object.entries(s.quests).map(([id,qs])=>{let q=RF.DATA.quests[id];return `<div class="row quest ${qs.done?'done':''}"><div class="meta"><div class="questTitle"><b>${q.name}</b><span class="tag">${qs.done?'DONE':'ACTIVE'}</span></div><small>${q.desc}</small>${q.objectives.map(o=>`<div class="objective">${this.objDone(s,o)?'✅':'⬜'} ${o.text}</div>`).join('')}</div></div>`}).join('')}</div></section>`},
  objDone(s,o){if(o.type==='visit')return !!s.visited[o.target];if(o.type==='skill')return s.skills[o.target].level>=o.value;if(o.type==='flag')return !!s.flags[o.target];if(o.type==='item')return (s.inventory[o.target]||0)>=o.value;if(o.type==='kill')return (s.kills[o.target]||0)>=o.value;return false},
  shop(s){let l=RF.DATA.locations[s.location];if(!l.shop)return `<section class="card"><h2>Shop</h2><div class="notice">There is no permanent shop here. Return to Greenvale or wait for a travelling merchant.</div></section>`;return `<section class="card"><h2>Greenvale General Store</h2><div class="sub">Prices are basic in V1. Trading will become more dynamic later.</div><div class="list" style="margin-top:10px">${RF.DATA.shopStock.map(id=>{let it=RF.DATA.items[id],price=Math.max(1,Math.round(it.value*(1.35-(s.skills.trading.level-1)*.01)));return `<div class="row"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>${it.desc}</small></div><span class="qty">${price}g</span><button data-buy="${id}" data-price="${price}" ${s.gold>=price?'':'disabled'}>Buy</button></div>`}).join('')}</div></section><section class="card"><h3>Sell</h3><div class="list">${Object.entries(s.inventory).filter(([id])=>RF.DATA.items[id]?.value>0).map(([id,q])=>{let it=RF.DATA.items[id],price=Math.max(1,Math.floor(it.value*.55));return `<div class="row"><div class="icon">${it.icon}</div><div class="meta"><b>${it.name}</b><small>Owned: ${q}</small></div><span class="qty">${price}g</span><button data-sell="${id}" data-price="${price}">Sell 1</button></div>`}).join('')}</div></section>`},
  modalHtml(s){let m=this.modal;if(m.type==='event'){return `<div class="modalBack"><div class="modal"><div style="font-size:42px">${m.event.icon||'❗'}</div><h2>${m.event.title}</h2><div class="sub">${m.event.text}</div><div class="choices">${m.event.choices.map((c,i)=>`<button class="choice" data-choice="${i}" ${c.condition&&!c.condition(s)?'disabled':''}><b>${c.text}</b>${c.sub?`<small>${c.sub}</small>`:''}</button>`).join('')}</div></div></div>`}if(m.type==='message')return `<div class="modalBack"><div class="modal"><h2>${m.title}</h2><div class="sub">${m.text}</div><div class="choices"><button class="choice" data-close>Continue</button></div></div></div>`;return''},
  bind(s){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.render(s)});document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>RF.setSpeed(+b.dataset.speed));document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>RF.travel(b.dataset.travel));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>RF.action(b.dataset.action));document.querySelector('[data-cancel]')?.addEventListener('click',()=>RF.cancelActivity());document.querySelectorAll('[data-combat]').forEach(b=>b.onclick=()=>RF.combatAction(b.dataset.combat));document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>RF.craft(b.dataset.craft));document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>RF.equip(b.dataset.equip));document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>RF.useItem(b.dataset.use));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>RF.buy(b.dataset.buy,+b.dataset.price));document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>RF.sell(b.dataset.sell,+b.dataset.price));document.querySelector('[data-export]')?.addEventListener('click',()=>RF.exportPrompt());document.querySelector('[data-import]')?.addEventListener('click',()=>RF.importPrompt());document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>RF.resolveEvent(+b.dataset.choice));document.querySelector('[data-close]')?.addEventListener('click',()=>{this.modal=null;this.render(s)})}
};
